// Copyright 2026 the AAI authors. MIT license.
/// <reference types="vite/client" />
/**
 * The escape-hatch ratchet must never scan MARKDOWN.
 *
 * `scripts/check-escape-hatches.mjs` greps plain substrings and has no notion
 * of code versus prose, so every doc that *discusses* a suppression is scored
 * as one.
 *
 * That is not hypothetical. `CHANGELOG.md` is generated by changesets from
 * changeset summaries, and the summary for #996 described fixing this very
 * script's own cast patterns. Rendering it produced a hit in
 * `packages/aai/CHANGELOG.md`, which failed the Version Packages PR by two —
 * a gate failure on a file no human wrote, invisible at review time, blocking
 * every release whose changesets happen to name a pattern. The scaffold guide
 * carries the milder version: a sentence about setting provider keys "the
 * same way as ... secret" reads as a cast to a substring matcher, and sat in
 * the baseline as a phantom for months.
 *
 * So this suite asserts both halves of the argument: that the SHIPPED patterns
 * really do match ordinary prose in this repo's own markdown (the hazard is
 * real, not theoretical), and that the script therefore excludes markdown (the
 * fix is still in place). Testing only the second half would pass just as
 * happily if the patterns were quietly narrowed to something prose could never
 * trip.
 *
 * Note this file deliberately contains NO literal pattern text — it parses the
 * patterns out of the script and finds prose by scanning a real guide. Spelling
 * them out here would make this the second file whose source is a list of the
 * patterns, and it would need its own exclusion exactly as the script does.
 *
 * It lives in aai-templates for the same reason `claude-md-limit.test.ts`
 * does: the package already owns the tests for repo-level scripts, and raw
 * imports reach a sibling script with no node types — this package's tsconfig
 * has none.
 */

import { describe, expect, test } from "vitest";

const script = import.meta.glob("../../scripts/check-escape-hatches.mjs", {
  query: "?raw",
  import: "default",
  eager: true,
})["../../scripts/check-escape-hatches.mjs"];

/** A real, human-written guide in this repo — prose, not code. */
const scaffoldGuide = import.meta.glob("./scaffold/CLAUDE.md", {
  query: "?raw",
  import: "default",
  eager: true,
})["./scaffold/CLAUDE.md"];

/**
 * The committed per-file budgets the gate now checks against.
 *
 * Imported as JSON rather than raw so a syntax error in the baseline fails
 * here, in the ordinary test run, instead of at the next `pnpm check:hatches`.
 */
const baseline: Record<string, unknown> =
  Object.values(
    import.meta.glob<Record<string, unknown>>("../../scripts/escape-hatch-baseline.json", {
      import: "default",
      eager: true,
    }),
  )[0] ?? {};

/**
 * Pull the gate's patterns out of its source: entries read
 * `{ label: "...", re: "..." }`. Parsed rather than duplicated so this suite
 * tests what actually ships.
 */
function shippedPatterns(source: string): { label: string; re: string }[] {
  const entries = [...source.matchAll(/\{\s*label:\s*"([^"]+)",\s*re:\s*"([^"]*)"\s*\}/g)];
  return entries.map(([, label, re]) => ({ label: label ?? "", re: re ?? "" }));
}

describe("escape-hatch ratchet scope", () => {
  test("the script and a real guide are readable", () => {
    expect(script, "scripts/check-escape-hatches.mjs not found").toBeTypeOf("string");
    expect(scaffoldGuide, "scaffold/CLAUDE.md not found").toBeTypeOf("string");
  });

  test("the shipped patterns parse", () => {
    const patterns = shippedPatterns(script ?? "");
    // Seven today. Asserting a floor rather than an exact count keeps this from
    // failing every time a pattern is legitimately added.
    expect(patterns.length).toBeGreaterThanOrEqual(7);
    for (const { label, re } of patterns) {
      expect(label, "a pattern entry parsed with an empty label").not.toBe("");
      expect(() => new RegExp(re), `pattern ${label} is not a valid regex`).not.toThrow();
    }
  });

  test("shipped patterns match this repo's own prose — which is why markdown is excluded", () => {
    const patterns = shippedPatterns(script ?? "");
    const lines = (scaffoldGuide ?? "").split("\n");

    const hits = lines.filter((line) => patterns.some(({ re }) => new RegExp(re).test(line)));

    // If this ever drops to zero the hazard has not gone away — far likelier a
    // pattern was narrowed or the guide reworded. Either way the reasoning
    // behind the exclusion needs re-checking, so fail loudly rather than let
    // the next test stand on nothing.
    expect(
      hits.length,
      "no line of the scaffold guide matches any pattern — re-check why markdown is excluded",
    ).toBeGreaterThan(0);
  });

  test("markdown is excluded from the scan", () => {
    // git pathspec exclusions, matched against the same roots the scan walks.
    expect(script, "packages markdown is no longer excluded").toContain(':!packages/**/*.md"');
    expect(script, "scripts markdown is no longer excluded").toContain(':!scripts/**/*.md"');
  });

  test("built output and the pattern-listing files stay excluded", () => {
    // Asserted so a rewrite of PATHSPECS cannot drop them silently: `dist/`
    // would count shipped bundles, and two files in the repo have a list of
    // the patterns as their content — the script itself, and the baseline,
    // whose per-pattern keys scored as four fresh hatches on the first run
    // after the per-file conversion.
    expect(script).toContain(':!packages/**/dist/**"');
    expect(script).toContain(':!scripts/check-escape-hatches.mjs"');
    expect(script).toContain(':!scripts/escape-hatch-baseline.json"');
  });

  test("the baseline covers every shipped pattern that has occurrences", () => {
    // A pattern missing from the baseline is not an error (zero occurrences is
    // the goal), but a pattern the baseline has never heard of, holding
    // hundreds of hits, would mean the JSON and the script had drifted apart.
    const labels = new Set(shippedPatterns(script ?? "").map((p) => p.label));
    expect(labels.size).toBeGreaterThanOrEqual(7);
    for (const key of Object.keys(baseline)) {
      if (key.startsWith("_")) continue;
      expect(labels, `baseline names "${key}", which is not a shipped pattern`).toContain(key);
    }
  });

  test("the gate does not depend on git history", () => {
    // It used to: the previous version resolved a merge base with origin/main
    // and, failing that, printed "skipping ratchet" and exited 0 — a gate
    // reporting success while checking nothing, in exactly the environments
    // that get one commit of history (shallow CI clones, fresh worktrees).
    //
    // Asserted on the ARGV literal, not the word: the script's header explains
    // at length why merge-base was abandoned, so a substring match on
    // "merge-base" would be testing the prose. `["merge-base"` can only be a
    // call.
    expect(script, "the ratchet invokes git merge-base again").not.toContain('["merge-base"');
    // And the positive half — a test that only forbids the old mechanism would
    // pass just as well if the new one were deleted too.
    expect(script, "the ratchet no longer reads the committed baseline").toContain(
      "escape-hatch-baseline.json",
    );
  });

  test("--update refuses to raise a count", () => {
    // `--update` exists so giving headroom back is one command. If it also
    // blessed additions, the ratchet would be advisory: every failure would
    // have a one-command bypass, and the reviewable diff — the actual control
    // on a deliberate increase — would never be produced.
    expect(script).toContain("refusing to RAISE");
  });
});
