// Copyright 2026 the AAI authors. MIT license.
/// <reference types="vite/client" />
/**
 * The escape-hatch ratchet must never scan MARKDOWN.
 *
 * `scripts/check-escape-hatches.mjs` greps plain substrings and has no notion
 * of code versus prose, so every doc that *discusses* a suppression is scored
 * as one.
 *
 * That is not hypothetical. `CHANGELOG.md` is generated by changesets from
 * changeset summaries, and the summary for #996 described fixing this very
 * script's own cast patterns. Rendering it produced a hit in
 * `packages/aai/CHANGELOG.md`, which failed the Version Packages PR by two —
 * a gate failure on a file no human wrote, invisible at review time, blocking
 * every release whose changesets happen to name a pattern. The scaffold guide
 * carries the milder version: a sentence about setting provider keys "the
 * same way as ... secret" reads as a cast to a substring matcher, and sat in
 * the baseline as a phantom for months.
 *
 * So this suite asserts both halves of the argument: that the SHIPPED patterns
 * really do match ordinary prose in this repo's own markdown (the hazard is
 * real, not theoretical), and that the script therefore excludes markdown (the
 * fix is still in place). Testing only the second half would pass just as
 * happily if the patterns were quietly narrowed to something prose could never
 * trip.
 *
 * Note this file deliberately contains NO literal pattern text — it parses the
 * patterns out of the script and finds prose by scanning a real guide. Spelling
 * them out here would make this the second file whose source is a list of the
 * patterns, and it would need its own exclusion exactly as the script does.
 *
 * It lives in aai-templates for the same reason `claude-md-limit.test.ts`
 * does: the package already owns the tests for repo-level scripts, and raw
 * imports reach a sibling script with no node types — this package's tsconfig
 * has none.
 */

import { describe, expect, test } from "vitest";

const script = import.meta.glob("../../scripts/check-escape-hatches.mjs", {
  query: "?raw",
  import: "default",
  eager: true,
})["../../scripts/check-escape-hatches.mjs"];

/** A real, human-written guide in this repo — prose, not code. */
const scaffoldGuide = import.meta.glob("./scaffold/CLAUDE.md", {
  query: "?raw",
  import: "default",
  eager: true,
})["./scaffold/CLAUDE.md"];

/**
 * Pull the gate's patterns out of its source: entries read
 * `{ label: "...", re: "..." }`. Parsed rather than duplicated so this suite
 * tests what actually ships.
 */
function shippedPatterns(source: string): { label: string; re: string }[] {
  const entries = [...source.matchAll(/\{\s*label:\s*"([^"]+)",\s*re:\s*"([^"]*)"\s*\}/g)];
  return entries.map(([, label, re]) => ({ label: label ?? "", re: re ?? "" }));
}

describe("escape-hatch ratchet scope", () => {
  test("the script and a real guide are readable", () => {
    expect(script, "scripts/check-escape-hatches.mjs not found").toBeTypeOf("string");
    expect(scaffoldGuide, "scaffold/CLAUDE.md not found").toBeTypeOf("string");
  });

  test("the shipped patterns parse", () => {
    const patterns = shippedPatterns(script ?? "");
    // Seven today. Asserting a floor rather than an exact count keeps this from
    // failing every time a pattern is legitimately added.
    expect(patterns.length).toBeGreaterThanOrEqual(7);
    for (const { label, re } of patterns) {
      expect(label, "a pattern entry parsed with an empty label").not.toBe("");
      expect(() => new RegExp(re), `pattern ${label} is not a valid regex`).not.toThrow();
    }
  });

  test("shipped patterns match this repo's own prose — which is why markdown is excluded", () => {
    const patterns = shippedPatterns(script ?? "");
    const lines = (scaffoldGuide ?? "").split("\n");

    const hits = lines.filter((line) => patterns.some(({ re }) => new RegExp(re).test(line)));

    // If this ever drops to zero the hazard has not gone away — far likelier a
    // pattern was narrowed or the guide reworded. Either way the reasoning
    // behind the exclusion needs re-checking, so fail loudly rather than let
    // the next test stand on nothing.
    expect(
      hits.length,
      "no line of the scaffold guide matches any pattern — re-check why markdown is excluded",
    ).toBeGreaterThan(0);
  });

  test("markdown is excluded from the scan", () => {
    // git pathspec exclusions, matched against the same roots the scan walks.
    expect(script, "packages markdown is no longer excluded").toContain(':!packages/**/*.md"');
    expect(script, "scripts markdown is no longer excluded").toContain(':!scripts/**/*.md"');
  });

  test("built output and the script's own source stay excluded", () => {
    // Pre-existing exclusions, asserted so a rewrite of PATHSPECS cannot drop
    // them silently: `dist/` would count shipped bundles, and the script is the
    // one remaining file whose source is a list of the patterns.
    expect(script).toContain(':!packages/**/dist/**"');
    expect(script).toContain(':!scripts/check-escape-hatches.mjs"');
  });
});
