packages:
  - packages/*
  - docs

catalog:
  '@hono/zod-validator': ^0.9.0
  '@tailwindcss/vite': ^4.3.3
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.2
  '@types/json-schema': ^7.0.15
  '@types/mime-types': ^3.0.1
  '@types/node': ^26.2.0
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  '@types/ws': ^8.18.1
  '@vitejs/plugin-react': ^6.0.5
  ai: ^7.0.65
  clsx: ^2.1.1
  eventsource-parser: ^4.0.0
  fast-check: ^4.9.0
  hono: ^4.13.2
  jsdom: ^30.0.1
  mime-types: ^3.0.2
  nanoevents: ^10.0.0
  p-timeout: ^7.0.1
  react: ^19.2.8
  react-dom: ^19.2.8
  tailwindcss: ^4.3.3
  tsdown: ^0.22.14
  typescript: ^7.0.2
  ulid: ^3.0.2
  use-stick-to-bottom: ^1.1.6
  vite: ^8.2.1
  vitest: ^4.1.10
  ws: ^8.21.3
  xstate: ^5.32.5
  zod: ^4.4.3

catalogs:
  typedoc:
    typescript: ~6.0.0

ignoredBuiltDependencies:
  - esbuild
  - lefthook

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - protobufjs

overrides:
  unrun: 0.2.39

patchedDependencies:
  '@workflow/core@4.8.2': patches/@workflow__core@4.8.2.patch
  '@workflow/world-local@4.2.4': patches/@workflow__world-local@4.2.4.patch
  cbor-x@1.6.0: patches/cbor-x@1.6.0.patch
  cbor-x@1.6.5: patches/cbor-x@1.6.5.patch
