/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  plugins: ["@stryker-mutator/vitest-runner"],
  mutate: [
    "packages/aai/sdk/protocol.ts",
    "packages/aai/sdk/manifest.ts",
    "packages/aai/sdk/_internal-types.ts",
    "packages/aai/sdk/system-prompt.ts",
    "packages/aai/host/**/*.ts",
    "packages/aai-server/ndjson-transport.ts",
    "packages/aai-server/orchestrator.ts",
    "packages/aai-server/sandbox.ts",
    "packages/aai-server/sandbox-vm.ts",
    "packages/aai-server/ssrf.ts",
    "packages/aai-server/secrets.ts",
    "packages/aai-server/middleware.ts",
    "packages/aai-server/bundle-store.ts",
    "packages/aai-cli/_api-client.ts",
    "packages/aai-cli/_bundler.ts",
    "packages/aai-cli/_config.ts",
    "packages/aai-cli/_deploy.ts",
    "packages/aai-cli/_init.ts",
    "packages/aai-cli/_dev-server.ts",
    "packages/aai-cli/_templates.ts",
    "packages/aai-cli/secret.ts",
    "!**/*.test.ts",
    "!**/*.test-d.ts",
    "!**/_test-*.ts",
    "!**/*-barrel.ts",
    "!**/fixtures/**",
    "!**/index.ts",
    "!packages/aai/host/testing.ts",
    "!packages/aai/host/matchers.ts",
  ],
  testRunner: "vitest",
  testRunnerNodeArgs: ["--experimental-vm-modules"],
  reporters: ["html", "clear-text", "progress"],
  htmlReporter: { fileName: "reports/mutation/index.html" },
  thresholds: { high: 70, low: 50, break: 40 },
  incremental: true,
  incrementalFile: ".stryker-incremental.json",
  concurrency: 4,
  timeoutMS: 60000,
};
