import { tool } from "aai";
import { z } from "zod";
import type { KV } from "../_shared.ts";
import {
  checkChaosInterrupt,
  creativitySeed,
  d,
  getGameState,
  pick,
  saveGameState,
} from "../_shared.ts";

export const oracle = tool({
  description:
    "Consult the oracle for narrative inspiration. Generates random prompts from thematic tables.",
  parameters: z.object({
    type: z
      .enum(["action_theme", "npc_reaction", "scene_twist", "yes_no", "chaos_check"])
      .describe("Type of oracle consultation"),
  }),
  async execute(args, ctx: { kv: KV }) {
    const state = await getGameState(ctx.kv);

    if (args.type === "yes_no") {
      const roll = d(6);
      const answer = roll <= 2 ? "No" : roll <= 4 ? "Yes, but with a complication" : "Yes";
      return { type: "yes_no", roll, answer };
    }

    if (args.type === "chaos_check") {
      const interrupt = checkChaosInterrupt(state);
      await saveGameState(ctx.kv, state);
      return {
        type: "chaos_check",
        chaosFactor: state.chaosFactor,
        interrupted: Boolean(interrupt),
        interruptType: interrupt,
      };
    }

    if (args.type === "npc_reaction") {
      const reactions = [
        "Acts on their agenda",
        "Reveals a secret",
        "Makes a demand",
        "Offers unexpected help",
        "Betrays expectations",
        "Shows vulnerability",
        "Escalates the conflict",
        "Withdraws or retreats",
        "Changes their stance",
        "Introduces a new complication",
      ];
      return { type: "npc_reaction", reaction: pick(reactions) };
    }

    if (args.type === "scene_twist") {
      const twists = [
        "A hidden connection is revealed",
        "The environment shifts dramatically",
        "An NPC's true motives surface",
        "Time pressure intensifies",
        "An old enemy reappears",
        "A resource is discovered or lost",
        "The rules of the world bend",
        "An alliance fractures",
        "A prophecy or omen manifests",
        "The stakes escalate unexpectedly",
      ];
      return { type: "scene_twist", twist: pick(twists) };
    }

    // action_theme (default)
    const actions = [
      "Abandon",
      "Advance",
      "Assault",
      "Betray",
      "Block",
      "Bolster",
      "Breach",
      "Capture",
      "Challenge",
      "Change",
      "Clash",
      "Command",
      "Compel",
      "Conceal",
      "Confront",
      "Control",
      "Corrupt",
      "Create",
      "Deceive",
      "Defend",
      "Defy",
      "Deliver",
      "Demand",
      "Depart",
      "Destroy",
      "Distract",
      "Endure",
      "Escape",
      "Explore",
      "Falter",
      "Find",
      "Follow",
      "Forge",
      "Forsake",
      "Gather",
      "Guard",
      "Guide",
      "Harm",
      "Hide",
      "Hold",
      "Hunt",
      "Investigate",
      "Journey",
      "Learn",
      "Leave",
      "Locate",
      "Lose",
      "Manipulate",
      "Move",
      "Oppose",
      "Overwhelm",
      "Persevere",
      "Plunder",
      "Preserve",
      "Protect",
      "Rage",
      "Reach",
      "Reclaim",
      "Refuse",
      "Reject",
      "Release",
      "Repair",
      "Resist",
      "Restore",
      "Reveal",
      "Risk",
      "Salvage",
      "Scheme",
      "Search",
      "Secure",
      "Seize",
      "Serve",
      "Share",
      "Shatter",
      "Shelter",
      "Strengthen",
      "Summon",
      "Surrender",
      "Surround",
      "Survive",
      "Swear",
      "Threaten",
      "Track",
      "Transform",
      "Trap",
      "Traverse",
      "Uncover",
      "Uphold",
      "Weaken",
      "Withdraw",
    ];
    const themes = [
      "Ancestor",
      "Ash",
      "Beast",
      "Blood",
      "Bone",
      "Burden",
      "Communion",
      "Corruption",
      "Crown",
      "Darkness",
      "Death",
      "Debt",
      "Decay",
      "Despair",
      "Divinity",
      "Doom",
      "Dream",
      "Dynasty",
      "Eclipse",
      "Exile",
      "Faith",
      "Fate",
      "Flesh",
      "Fury",
      "Grace",
      "Grief",
      "Guilt",
      "Heritage",
      "Hollow",
      "Honor",
      "Horror",
      "Hunger",
      "Iron",
      "Judgment",
      "Kingdom",
      "Knowledge",
      "Legacy",
      "Loss",
      "Madness",
      "Memory",
      "Mercy",
      "Monster",
      "Mystery",
      "Night",
      "Oath",
      "Omen",
      "Order",
      "Passage",
      "Peril",
      "Plague",
      "Power",
      "Pride",
      "Prophecy",
      "Rebirth",
      "Relic",
      "Rot",
      "Ruin",
      "Sacrifice",
      "Scar",
      "Secret",
      "Shadow",
      "Shard",
      "Silence",
      "Sorrow",
      "Spirit",
      "Splendor",
      "Storm",
      "Throne",
      "Time",
      "Treachery",
      "Truth",
      "Valor",
      "Vengeance",
      "War",
      "Waste",
      "Winter",
      "Wisdom",
      "Wound",
    ];
    return {
      type: "action_theme",
      action: pick(actions),
      theme: pick(themes),
      seed: creativitySeed(),
    };
  },
});
