// Copyright 2026 the AAI authors. MIT license.
/**
 * Internals of the studio-workspace commands (`aai list/pull/push/publish`):
 * the local source-file walk and the thin clients for the platform's
 * `/studio/projects` routes. The workspace is the single source of truth —
 * these helpers only move files between a local directory and the project's
 * workspace row; production deploys happen exclusively through the studio's
 * Publish route (which runs the deploy machinery in the project's sandbox).
 */

import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import { PREVIEW_SLUG_SUFFIX, VALID_SLUG_RE } from "@alexkroman1/aai/utils";
import { apiRequest } from "./_api-client.ts";

/**
 * Mirrors of the studio workspace caps (`aai-studio-server/studio-limits.ts`)
 * — by value, like `aai-guest/limits.ts`, since the CLI cannot depend on the
 * private server package. The server re-validates every push; these exist so
 * an oversized file is a named warning locally instead of a rejected upload.
 */
export const MAX_STUDIO_FILE_BYTES = 256_000;
export const MAX_STUDIO_FILES = 100;

/**
 * What never syncs to a workspace — the same set the guest's snapshot skips
 * (`aai-guest/studio-workspace-fs.ts`), plus what only exists locally:
 * secrets (`.env` rides the secret routes, never a workspace row) and
 * lockfiles (regenerated by install, noise in the studio editor).
 */
const IGNORED_DIRS = new Set(["node_modules", ".git", "dist", ".aai"]);
const IGNORED_FILES = [
  /^\.env(\..+)?$/,
  /^pnpm-lock\.yaml$/,
  /^package-lock\.json$/,
  /^yarn\.lock$/,
  /^\.DS_Store$/,
];

function isIgnoredFile(name: string): boolean {
  return IGNORED_FILES.some((re) => re.test(name));
}

/** Project-relative paths of every syncable file under `dir`, sorted. */
async function walkProject(dir: string, current = dir): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue;
    const abs = path.join(current, entry.name);
    if (entry.isDirectory()) {
      if (!IGNORED_DIRS.has(entry.name)) out.push(...(await walkProject(dir, abs)));
    } else if (entry.isFile() && !isIgnoredFile(entry.name)) {
      out.push(path.relative(dir, abs));
    }
  }
  return out.sort((a, b) => a.localeCompare(b));
}

/**
 * Decode `buf` as UTF-8, or null when it isn't valid UTF-8.
 *
 * `fatal` makes an invalid sequence throw instead of becoming U+FFFD, which
 * is the whole point: a workspace is a JSON path→string map and cannot carry
 * arbitrary bytes, so a lossy read turned a pushed PNG into replacement
 * characters while reporting success — and a later `aai pull` wrote the
 * mangled version back over the local original. `ignoreBOM` keeps a leading
 * U+FEFF in the string; without it the decoder strips the BOM and the check
 * meant to stop corruption would quietly perform some of its own.
 */
const UTF8_STRICT = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true });
function decodeUtf8(buf: Buffer): string | null {
  try {
    return UTF8_STRICT.decode(buf);
  } catch {
    return null;
  }
}

/**
 * Walk a local project into the path→content record a workspace stores —
 * the CLI-side twin of the guest's `snapshotWorkspace`: same ignored
 * directories, same caps, oversized and non-text files skipped with a
 * warning rather than failing the whole push.
 */
export async function collectSourceFiles(
  dir: string,
): Promise<{ files: Record<string, string>; warnings: string[] }> {
  const paths = await walkProject(dir);
  const files: Record<string, string> = {};
  const warnings: string[] = [];
  if (paths.length > MAX_STUDIO_FILES) {
    warnings.push(
      `Project has ${paths.length} files; only the first ${MAX_STUDIO_FILES} sync to the studio.`,
    );
  }
  for (const rel of paths.slice(0, MAX_STUDIO_FILES)) {
    const abs = path.join(dir, rel);
    const st = await stat(abs);
    if (st.size > MAX_STUDIO_FILE_BYTES) {
      warnings.push(`${rel} is ${st.size} bytes (max ${MAX_STUDIO_FILE_BYTES}) — not synced.`);
      continue;
    }
    const content = decodeUtf8(await readFile(abs));
    if (content === null) {
      warnings.push(`${rel} is not valid UTF-8 (binary file?) — not synced.`);
      continue;
    }
    // Workspace paths are POSIX; keep pushes from Windows checkouts valid.
    files[rel.split(path.sep).join("/")] = content;
  }
  return { files, warnings };
}

/**
 * A studio project name derived from a directory name, or null if unusable.
 *
 * A `-preview` suffix is deliberately unusable. Publishing a project deploys
 * it under the project's own name, so a `*-preview` project would claim a
 * slug the studio's orphan-preview sweep reaps hourly — deleting the agent,
 * its app-database schema, and its secrets on a schedule the user never
 * asked for. Refusing the name is recoverable (rename the directory); losing
 * a published agent to the reaper is not.
 */
export function projectNameFromDir(dir: string): string | null {
  const name = path
    .basename(dir)
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "")
    .slice(0, 64);
  if (name.endsWith(PREVIEW_SLUG_SUFFIX)) return null;
  return VALID_SLUG_RE.test(name) ? name : null;
}

/** The shareable studio URL for a project — what every command prints. */
export function studioProjectUrl(serverUrl: string, project: string): string {
  return `${serverUrl}/studio/chat/${project}`;
}

/** `GET /studio/projects/:project` — see `projectPayload` server-side. */
export type StudioProject = {
  files: Record<string, string>;
  sourceHash: string;
  deployedSlug?: string;
  unpublished?: boolean;
};

export function listStudioProjects(serverUrl: string, apiKey: string): Promise<string[]> {
  return apiRequest<{ projects: string[] }>(`${serverUrl}/studio/projects`, {
    apiKey,
    action: "list",
  }).then((res) => res.projects);
}

/** Fetch a project, or null when it doesn't exist (the push existence probe). */
export function fetchStudioProject(
  serverUrl: string,
  apiKey: string,
  project: string,
): Promise<StudioProject | null> {
  return apiRequest<StudioProject | null>(
    `${serverUrl}/studio/projects/${encodeURIComponent(project)}`,
    { apiKey, action: "pull", allow404: true },
  );
}

/** `PUT /studio/projects/:project/source` — the atomic whole-tree push. */
export function pushStudioSource(
  serverUrl: string,
  apiKey: string,
  project: string,
  body: { files: Record<string, string>; baseHash?: string | undefined },
): Promise<{ sourceHash: string; created: boolean }> {
  return apiRequest(`${serverUrl}/studio/projects/${encodeURIComponent(project)}/source`, {
    apiKey,
    action: "push",
    method: "PUT",
    body,
    // Not idempotent in effect (a retried create can double-fire previews),
    // but a replayed identical push is a no-op server-side, so retries are
    // safe — keep the default transient-failure retry.
    hints: {
      409: "The studio has newer changes. Run `aai pull` to fetch them, or `aai push --force` to overwrite.",
    },
  });
}

/** `POST /studio/projects/:project/deploy` — Publish, in the project's sandbox. */
export function publishStudioProject(
  serverUrl: string,
  apiKey: string,
  project: string,
): Promise<{ ok: true; slug: string; url: string; output: string }> {
  return apiRequest(`${serverUrl}/studio/projects/${encodeURIComponent(project)}/deploy`, {
    apiKey,
    action: "publish",
    method: "POST",
    // A retried publish re-runs a whole in-sandbox build; surface the
    // failure instead.
    retry: 0,
  });
}
