// Copyright 2026 the AAI authors. MIT license.
/**
 * FROZEN authoring example — `aai:testing`, epoch 7.
 *
 * Epoch 8 moved with `AgentDef` gaining `temperature`. The testing surface
 * itself is unchanged, so epoch 7 still stands.
 *
 * Do not edit this file to make a compile error go away; the error IS the
 * finding.
 */

import { z } from "zod";
import { agent, type ToolContext, tool } from "../../../index.ts";
import { createToolContext, runTool, toolOf } from "../../../sdk/testing.ts";

const priceOf = tool({
  description: "Price a SKU",
  inputSchema: z.object({ sku: z.string() }),
  execute: ({ sku }) => ({ sku, price: 42 }),
});

const def = agent({ name: "Shop" });

/** The inert context, and the overrides a spec supplies. */
export function contexts(): [ToolContext, ToolContext] {
  return [createToolContext(), createToolContext({ sessionId: "s-1", env: { SHOP: "on" } })];
}

/** Running a tool through the registry, the epoch-6 way. */
export async function run(): Promise<unknown> {
  const withTool = { ...def, tools: { price_of: priceOf } };
  const found = toolOf(withTool, "price_of");
  void found;
  return await runTool(withTool, "price_of", { sku: "abc" }, createToolContext());
}
