// Copyright 2026 the AAI authors. MIT license.
/// <reference types="vite/client" />
/**
 * The escape-hatch ratchet must never scan MARKDOWN.
 *
 * `scripts/check-escape-hatches.mjs` greps plain substrings and has no notion
 * of code versus prose, so every doc that *discusses* a suppression is scored
 * as one.
 *
 * That is not hypothetical. `CHANGELOG.md` is generated by changesets from
 * changeset summaries, and the summary for #996 described fixing this very
 * script's own cast patterns. Rendering it produced a hit in
 * `packages/aai/CHANGELOG.md`, which failed the Version Packages PR by two —
 * a gate failure on a file no human wrote, invisible at review time, blocking
 * every release whose changesets happen to name a pattern. The scaffold guide
 * carries the milder version: a sentence about setting provider keys "the
 * same way as ... secret" reads as a cast to a substring matcher, and sat in
 * the baseline as a phantom for months.
 *
 * So this suite asserts both halves of the argument: that the SHIPPED patterns
 * really do match ordinary prose in this repo's own markdown (the hazard is
 * real, not theoretical), and that the script therefore excludes markdown (the
 * fix is still in place). Testing only the second half would pass just as
 * happily if the patterns were quietly narrowed to something prose could never
 * trip.
 *
 * Note this file deliberately contains NO literal pattern text — it parses the
 * patterns out of the script and finds prose by scanning a real guide. Spelling
 * them out here would make this the second file whose source is a list of the
 * patterns, and it would need its own exclusion exactly as the script does.
 *
 * It lives in aai-templates for the same reason `claude-md-limit.test.ts`
 * does: the package already owns the tests for repo-level scripts, and raw
 * imports reach a sibling script with no node types — this package's tsconfig
 * has none.
 */

import { describe, expect, test } from "vitest";
import { ERE_UNSUPPORTED, sole } from "./_gate-support.ts";

const script = sole(
  import.meta.glob("../../../scripts/check-escape-hatches.mjs", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
);

/**
 * The shared ratchet ENGINE, which both baseline gates now run on.
 *
 * Read separately because this spec works by scraping gate source for the
 * mechanisms it must keep: when the two ratchets converged onto one engine,
 * every assertion about `--update`'s refuse-to-raise contract silently stopped
 * finding its string in `check-escape-hatches.mjs` and the test failed naming a
 * mechanism that had merely MOVED. A spec that scrapes has to be told where the
 * thing lives, which is the cost of scraping and the reason it is worth it here
 * — the alternative is trusting that a gate still contains its own gate.
 */
const engine = sole(
  import.meta.glob("../../../scripts/_ratchet.mjs", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
);

/** A real, human-written guide in this repo — prose, not code. */
const scaffoldGuide = sole(
  import.meta.glob("../scaffold/CLAUDE.md", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
);

/**
 * The whole markdown corpus the PER-PATTERN liveness assertion is made against:
 * the root guide and every package guide.
 *
 * The scaffold guide alone could not carry that assertion, which is how the
 * hole got there. Measured against it, `as any` matched one line and the other
 * six patterns matched ZERO — so an aggregate "some pattern matched" test was
 * satisfied by one live pattern while six could have been narrowed to something
 * inert, and the gate would have reported `now=0 ✓` over a tree full of
 * violations with this file staying green.
 *
 * Every guide here is prose that genuinely DISCUSSES suppressions: AGENTS.md's
 * ratchets section names each pattern by name, several of them repeatedly. A
 * pattern added without any prose naming it fails below, and the remedy is to
 * document it — which every pattern here already is.
 */
const proseDocs: Record<string, string> = {
  ...import.meta.glob<string>("../../../AGENTS.md", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
  ...import.meta.glob<string>("../../*/CLAUDE.md", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
  ...import.meta.glob<string>("../scaffold/CLAUDE.md", {
    query: "?raw",
    import: "default",
    eager: true,
  }),
};

/**
 * Every line of that corpus, tagged with the document it came from.
 *
 * Split ONCE, at module scope, rather than per call: the per-pattern liveness
 * case below reads it for each of the seven patterns, and the corpus is every
 * guide in the repo — half a megabyte of markdown re-split eight times for an
 * answer that cannot change between cases.
 */
const proseLines: { doc: string; line: string }[] = Object.entries(proseDocs).flatMap(
  ([doc, text]) => text.split("\n").map((line) => ({ doc, line })),
);

/**
 * The committed per-file budgets the gate now checks against.
 *
 * Imported as JSON rather than raw so a syntax error in the baseline fails
 * here, in the ordinary test run, instead of at the next `pnpm check:hatches`.
 */
const baseline: Record<string, unknown> =
  sole(
    import.meta.glob<Record<string, unknown>>("../../../scripts/escape-hatch-baseline.json", {
      import: "default",
      eager: true,
    }),
  ) ?? {};

/**
 * Pull the gate's patterns out of its source: entries read
 * `{ label: "...", re: "..." }`. Parsed rather than duplicated so this suite
 * tests what actually ships.
 */
function shippedPatterns(source: string): { label: string; re: string }[] {
  // COMMENT LINES ARE DROPPED FIRST. The script's own header explains this
  // parser by quoting the shape it looks for, so a naive scan reads the
  // explanation as an extra pattern — one whose `re` is an ellipsis, which then
  // satisfies every liveness assertion below against any prose containing an
  // ellipsis. A guard reading a gate's prose as the gate is the same mistake
  // this file exists to catch, arriving from inside.
  const code = source
    .split("\n")
    .filter((line) => !/^\s*(?:\/\/|\*|\/\*)/.test(line))
    .join("\n");
  const entries = [...code.matchAll(/\{\s*label:\s*"([^"]+)",\s*re:\s*"([^"]*)"\s*\}/g)];
  return entries.map(([, label, re]) => ({ label: label ?? "", re: re ?? "" }));
}

/** The shipped patterns, parsed once — four cases below read the same answer. */
const patterns = shippedPatterns(script ?? "");

describe("escape-hatch ratchet scope", () => {
  test("the script and the prose corpus are readable", () => {
    expect(script, "scripts/check-escape-hatches.mjs not found").toBeTypeOf("string");
    expect(scaffoldGuide, "scaffold/CLAUDE.md not found").toBeTypeOf("string");
    // A corpus floor, for the reason the ratchets themselves carry one: every
    // per-pattern assertion below is "this pattern found prose", and an empty
    // corpus turns all of them into statements about nothing.
    expect(Object.keys(proseDocs).length, "no guides found").toBeGreaterThanOrEqual(10);
    expect(proseLines.length, "the markdown corpus is empty").toBeGreaterThan(2000);
  });

  test("the shipped patterns parse", () => {
    // Seven today. Asserting a floor rather than an exact count keeps this from
    // failing every time a pattern is legitimately added.
    expect(patterns.length).toBeGreaterThanOrEqual(7);
    for (const { label, re } of patterns) {
      expect(label, "a pattern entry parsed with an empty label").not.toBe("");
      expect(() => new RegExp(re), `pattern ${label} is not a valid regex`).not.toThrow();
    }
  });

  test.each(patterns)(
    "pattern $label matches this repo's own prose — which is why markdown is excluded",
    ({ label, re }) => {
      // PER PATTERN, and that is the whole point of this test.
      //
      // This used to be one aggregate assertion — "some line matches some
      // pattern" — over the scaffold guide alone. Measured against that corpus,
      // `as any` matched one line and the other six matched ZERO, so a single
      // live pattern satisfied the entire suite: narrow six of them to
      // something that can never match and the gate reports `now=0 ✓` over a
      // tree full of violations while this spec stays green. That is the same
      // dead-pattern failure AGENTS.md records paying for with `\b`, and this
      // file is its home.
      //
      // A failure here is far likelier to be a narrowed pattern than a reworded
      // guide, but either way the reasoning behind the markdown exclusion needs
      // re-checking before this is "fixed" by deleting it.
      const hits = proseLines.filter(({ line }) => new RegExp(re).test(line));
      expect(
        hits.length,
        `pattern "${label}" matches no line of AGENTS.md or a package guide — ` +
          "either it has been narrowed to something inert, or the prose that " +
          "justifies excluding markdown from the scan is gone",
      ).toBeGreaterThan(0);
    },
  );

  test("no pattern uses a GNU-only regex construct", () => {
    // The engines DIFFER, and this is the mitigation for that.
    //
    // These patterns are validated above with JavaScript's `new RegExp`, while
    // `_ratchet.mjs` ships them to `git grep -nIE` — POSIX ERE, whose support
    // for GNU extensions varies by build. `\b` is the one already paid for
    // here: two patterns carried one, matched NOTHING on the machines where
    // git's matcher does not implement it, and the gate reported success over a
    // tree holding 110 violations. A JS-side regex test cannot detect that, so
    // the constructs ERE has no answer for are banned outright.
    //
    // The list is `ERE_UNSUPPORTED` in `_gate-support.ts`, shared with
    // `guard-invariants-gate.test.ts`'s twin ban over the rule patterns: a
    // construct added to one copy and not the other is a hole in whichever gate
    // was not updated. This file had no `\b` assertion at all, and its two most
    // complex patterns are the two that historically carried one.
    expect(patterns.length, "no patterns parsed").toBeGreaterThanOrEqual(7);
    for (const { label, re } of patterns) {
      for (const [construct, why] of ERE_UNSUPPORTED) {
        expect(re, `pattern "${label}" uses ${construct} — ${why}`).not.toContain(construct);
      }
    }
  });

  test("markdown is excluded from the scan", () => {
    // git pathspec exclusions, matched against the same roots the scan walks.
    expect(script, "packages markdown is no longer excluded").toContain(':!packages/**/*.md"');
    expect(script, "scripts markdown is no longer excluded").toContain(':!scripts/**/*.md"');
  });

  test("built output and the pattern-listing files stay excluded", () => {
    // Asserted so a rewrite of PATHSPECS cannot drop them silently: `dist/`
    // would count shipped bundles, and two files in the repo have a list of
    // the patterns as their content — the script itself, and the baseline,
    // whose per-pattern keys scored as four fresh hatches on the first run
    // after the per-file conversion.
    expect(script).toContain(':!packages/**/dist/**"');
    expect(script).toContain(':!scripts/check-escape-hatches.mjs"');
    expect(script).toContain(':!scripts/escape-hatch-baseline.json"');
  });

  test("the baseline covers every shipped pattern that has occurrences", () => {
    // A pattern missing from the baseline is not an error (zero occurrences is
    // the goal), but a pattern the baseline has never heard of, holding
    // hundreds of hits, would mean the JSON and the script had drifted apart.
    const labels = new Set(patterns.map((p) => p.label));
    expect(labels.size).toBeGreaterThanOrEqual(7);
    for (const key of Object.keys(baseline)) {
      if (key.startsWith("_")) continue;
      expect(labels, `baseline names "${key}", which is not a shipped pattern`).toContain(key);
    }
  });

  test("the gate does not depend on git history", () => {
    // It used to: the previous version resolved a merge base with origin/main
    // and, failing that, printed "skipping ratchet" and exited 0 — a gate
    // reporting success while checking nothing, in exactly the environments
    // that get one commit of history (shallow CI clones, fresh worktrees).
    //
    // Asserted on the ARGV literal, not the word: the script's header explains
    // at length why merge-base was abandoned, so a substring match on
    // "merge-base" would be testing the prose. `["merge-base"` can only be a
    // call.
    expect(script, "the ratchet invokes git merge-base again").not.toContain('["merge-base"');
    // And the positive half — a test that only forbids the old mechanism would
    // pass just as well if the new one were deleted too.
    expect(script, "the ratchet no longer reads the committed baseline").toContain(
      "escape-hatch-baseline.json",
    );
  });

  test("--update refuses to raise a count", () => {
    // `--update` exists so giving headroom back is one command. If it also
    // blessed additions, the ratchet would be advisory: every failure would
    // have a one-command bypass, and the reviewable diff — the actual control
    // on a deliberate increase — would never be produced.
    expect(engine).toContain("refusing to RAISE");
  });

  test("the gate still runs on the shared ratchet engine", () => {
    // The assertion above moved to `_ratchet.mjs`, so on its own it would now
    // pass for a gate that had stopped using the engine entirely — it would be
    // checking a file nothing runs. This is the other half.
    expect(script).toContain("_ratchet.mjs");
  });

  test("the top-level scripts/*.md exclusion is not lost", () => {
    // A git pathspec is fnmatch WITHOUT FNM_PATHNAME, so the literal slash in
    // `scripts/**/*.md` makes a subdirectory MANDATORY — it matched the files
    // under scripts/starter-eval/ and not one of the ~29 then at the top level.
    // (No subdirectory under scripts/ holds a .md today, so the nested spelling
    // matches nothing; both stay, for the next one that does.)
    // Both spellings are needed; deleting either silently re-opens the
    // CHANGELOG.md release-blocker this exclusion exists to prevent.
    expect(script).toContain(':!scripts/**/*.md"');
    expect(script).toContain(':!scripts/*.md"');
  });
});
