import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "index.ts",
    "types.ts",
    "kv.ts",
    "vector.ts",
    "server.ts",
    "protocol.ts",
    "s2s.ts",
    "session.ts",
    "runtime.ts",
    "worker-entry.ts",
    "ws-handler.ts",
    "direct-executor.ts",
    "builtin-tools.ts",
    "internal-types.ts",
    "telemetry.ts",
    "_mock-ws.ts",
    "testing.ts",
    "matchers.ts",
    "utils.ts",
  ],
  format: "esm",
  platform: "node",
  target: "node22",
  outDir: "dist",
  dts: false,
  outExtensions: () => ({ js: ".js" }),
  deps: { neverBundle: [/^[^./]/] },
});
