// Copyright 2026 the AAI authors. MIT license.
/**
 * Deployment TARGETS — what `aai build` emits beside the worker so a host can
 * run this project without the project holding anything host-specific.
 *
 * ## Why a target rather than a file in the scaffold
 *
 * Every host wants a different entry shape: Vercel wants a module whose default
 * export is an `http.Server` it binds itself, a container wants a long-lived
 * process, another platform wants something else again. Committing one of those
 * to the scaffold makes every project assert a fact that is load-bearing on
 * exactly one host — the same objection that removed `server.mjs`.
 *
 * Nitro is the worked precedent: one codebase, a preset per provider, and the
 * preset EMITS the host's expected shape into the build directory. `node-server`
 * is its default and Vercel/Netlify/Cloudflare are detected from the CI
 * environment with no configuration. Next does the same narrower thing with
 * `output: "standalone"` — it generates a `server.js` rather than asking anyone
 * to write one. Either way the user's repository contains no host file, which is
 * the property to preserve here.
 *
 * ## Auto-detection, and why it is safe
 *
 * A target is chosen with `--target`, or detected from the environment when the
 * flag is absent. Detection reads the variables the hosts set on their own build
 * containers ({@link TARGET_ENV_MARKERS}), so it only ever fires where the build
 * is genuinely running on that host — a laptop sets none of them and gets
 * {@link DEFAULT_BUILD_TARGET}, which emits nothing extra and is what every
 * existing project already does.
 */

/** The targets `aai build --target` accepts. */
export const BUILD_TARGETS = ["node", "vercel"] as const;

export type BuildTarget = (typeof BUILD_TARGETS)[number];

/**
 * What a build with no `--target` and no host environment produces: the worker
 * and the client, and nothing else.
 *
 * `node` rather than a `"none"` sentinel because it NAMES the deployment it
 * serves — a long-lived process running `aai start` — which is what every
 * container platform wants and what the scaffold's own `start` script runs.
 */
export const DEFAULT_BUILD_TARGET: BuildTarget = "node";

/**
 * The environment variable each host sets on its own build container.
 *
 * `VERCEL` is set for every Vercel build and deployment. Detection is per host
 * rather than a single "am I in CI" test, because a GitHub Action building a
 * container image is CI too and wants the default.
 */
export const TARGET_ENV_MARKERS: Readonly<Record<string, BuildTarget>> = {
  VERCEL: "vercel",
};

export function isBuildTarget(value: string): value is BuildTarget {
  return (BUILD_TARGETS as readonly string[]).includes(value);
}

/**
 * Resolve the target for this build: an explicit flag wins, then the
 * environment, then {@link DEFAULT_BUILD_TARGET}.
 *
 * An unrecognised `--target` is REFUSED naming what is accepted, rather than
 * falling back to the default — a typo'd target that silently built the default
 * would deploy a project missing the entry its host needs, and the failure would
 * arrive as a 404 from the platform rather than as an error from the build.
 */
export function resolveBuildTarget(
  explicit: string | undefined,
  env: Record<string, string | undefined> = process.env,
): BuildTarget {
  if (explicit !== undefined) {
    if (!isBuildTarget(explicit)) {
      throw new Error(`Unknown build target "${explicit}". Accepted: ${BUILD_TARGETS.join(", ")}.`);
    }
    return explicit;
  }
  for (const [marker, target] of Object.entries(TARGET_ENV_MARKERS)) {
    if (env[marker]) return target;
  }
  return DEFAULT_BUILD_TARGET;
}

/**
 * The Vercel function entry, emitted into the build output.
 *
 * `export default <http.Server>` is Vercel's documented Node WebSocket shape —
 * they bind the socket and deliver upgrades themselves — which is exactly what
 * `AgentServer.node` is, so the whole adapter is these few lines. It is
 * GENERATED rather than committed for the reason at the top of this module.
 *
 * Top-level `await` is deliberate and required: the platform reads the module's
 * default export, so the server has to exist by the time evaluation finishes.
 *
 * `process.cwd()` rather than a path relative to this file: Vercel runs a
 * function with the project root as the working directory, and the emitted file
 * sits at a depth that depends on where the platform relocates it.
 */
export const VERCEL_ENTRY_SOURCE = `// Generated by \`aai build --target vercel\` — do not edit, and do not commit.
// Vercel binds this server and delivers WebSocket upgrades to it; nothing here
// calls listen(). See @alexkroman1/aai-cli/start.
import { createProjectServer } from "@alexkroman1/aai-cli/start";

export default (await createProjectServer({ cwd: process.cwd() })).node;
`;

/**
 * The `vercel.json` the emitted entry needs.
 *
 * Two things it must say. The entry is a NODE function, not an edge one —
 * WebSockets need the Node runtime — and every request routes to it, because
 * this server serves its own static assets from `clientDir` and owns
 * `/websocket`, `/workflows/*` and the webhook path. Routing static files
 * through the CDN instead would be faster and is deliberately not attempted
 * here: it means the Build Output API, which is a much larger change than an
 * entry file, and it is not what makes a deployment work or not.
 */
export const VERCEL_CONFIG_SOURCE = `${JSON.stringify(
  {
    $schema: "https://openapi.vercel.sh/vercel.json",
    rewrites: [{ source: "/(.*)", destination: "/api/index" }],
  },
  null,
  2,
)}\n`;
