// Copyright 2026 the AAI authors. MIT license.
/**
 * `resolveBuildTarget` and the sources it emits.
 *
 * The property worth pinning is the PRECEDENCE, because two of its three arms
 * are invisible at a call site: a laptop build must not pick up a host target,
 * and a build ON a host must not need a flag the user has nowhere to pass. The
 * emitted sources are asserted for the two claims that make them work at all —
 * a default export and no `listen()`.
 */

import { describe, expect, test } from "vitest";
import {
  BUILD_TARGETS,
  DEFAULT_BUILD_TARGET,
  isBuildTarget,
  resolveBuildTarget,
  TARGET_ENV_MARKERS,
  VERCEL_CONFIG_SOURCE,
  VERCEL_ENTRY_SOURCE,
} from "./_build-target.ts";

describe("resolveBuildTarget", () => {
  test("a laptop with no host markers gets the default, which emits nothing", () => {
    expect(resolveBuildTarget(undefined, {})).toBe(DEFAULT_BUILD_TARGET);
    // The whole point of the default: an existing project's build is unchanged.
    expect(DEFAULT_BUILD_TARGET).toBe("node");
  });

  test("the host's own build container is detected with no flag", () => {
    // Vercel sets this on every build and deployment, so a project deployed
    // from a git push needs nothing configured — Nitro's zero-config property.
    expect(resolveBuildTarget(undefined, { VERCEL: "1" })).toBe("vercel");
  });

  test("an explicit target beats the environment, in both directions", () => {
    expect(resolveBuildTarget("node", { VERCEL: "1" })).toBe("node");
    expect(resolveBuildTarget("vercel", {})).toBe("vercel");
  });

  test("an unknown target is REFUSED, naming what is accepted", () => {
    // Never a fallback to the default: a typo that quietly built `node` would
    // deploy a project missing the entry its host needs, and the failure would
    // arrive as a 404 from the platform rather than an error from the build.
    expect(() => resolveBuildTarget("netlify", {})).toThrow(/Unknown build target "netlify"/);
    expect(() => resolveBuildTarget("netlify", {})).toThrow(/node, vercel/);
  });

  test("an empty marker value does not count as being on that host", () => {
    // `VERCEL=` in a shell is how somebody unsets it; reading it as truthy
    // would emit a Vercel entry on a laptop.
    expect(resolveBuildTarget(undefined, { VERCEL: "" })).toBe(DEFAULT_BUILD_TARGET);
  });

  test("every marker names a real target, and every target but the default is reachable", () => {
    // A marker naming a target that does not exist is dead detection, and a
    // target no marker and no flag can reach is a shape nobody can build.
    for (const target of Object.values(TARGET_ENV_MARKERS)) {
      expect(BUILD_TARGETS).toContain(target);
    }
    const detectable = new Set(Object.values(TARGET_ENV_MARKERS));
    for (const target of BUILD_TARGETS) {
      if (target === DEFAULT_BUILD_TARGET) continue;
      expect(detectable.has(target)).toBe(true);
    }
  });

  test("isBuildTarget narrows only the declared set", () => {
    expect(isBuildTarget("vercel")).toBe(true);
    expect(isBuildTarget("netlify")).toBe(false);
  });
});

describe("the emitted Vercel entry", () => {
  test("default-exports the node server and never calls listen", () => {
    // Both halves are the contract with the platform: it reads the default
    // export and binds the socket itself. A `listen()` here would bind a port
    // inside the function and serve nothing.
    expect(VERCEL_ENTRY_SOURCE).toMatch(/export default .*\.node;/);
    // Comments STRIPPED before the check: the file explains that it does not
    // call listen(), so a naive match reads its own explanation as the thing.
    const code = VERCEL_ENTRY_SOURCE.split("\n")
      .filter((line) => !line.trimStart().startsWith("//"))
      .join("\n");
    expect(code).not.toMatch(/\blisten\s*\(/);
    // Through the published subpath, not a relative path: this file is emitted
    // into a user's project, where `./start.ts` means nothing.
    expect(VERCEL_ENTRY_SOURCE).toContain('from "@alexkroman1/aai-cli/start"');
  });

  test("says it is generated, since it lands in a user's project", () => {
    expect(VERCEL_ENTRY_SOURCE).toMatch(/Generated by/);
    expect(VERCEL_ENTRY_SOURCE).toMatch(/do not edit/i);
  });

  test("the config routes everything to the entry", () => {
    const config = JSON.parse(VERCEL_CONFIG_SOURCE) as {
      rewrites: { source: string; destination: string }[];
    };
    // This server owns /websocket, /workflows/* and the webhook path and serves
    // its own static assets, so a partial route table would 404 exactly the
    // surfaces that are hardest to notice missing.
    expect(config.rewrites).toEqual([{ source: "/(.*)", destination: "/api/index" }]);
  });
});
