// Copyright 2026 the AAI authors. MIT license.
/**
 * The Deno target's emitted entry.
 *
 * The two claims that make it work at all — it BINDS, and it binds somewhere
 * the platform can reach — plus the two places its runtime differs from Node's.
 */

import { describe, expect, test } from "vitest";
import { DENO_ENTRY_SOURCE } from "./_deno-target.ts";

describe("the emitted Deno entry", () => {
  const code = DENO_ENTRY_SOURCE.split("\n")
    .filter((line) => !line.trimStart().startsWith("//"))
    .join("\n");

  test("BINDS, which every other target's entry must not", () => {
    // The one target whose host runs a long-lived process and expects it to
    // listen. Vercel's entry is a `(req, res)` handler and calling `listen()`
    // there would bind a port inside a function and serve nothing.
    expect(code).toMatch(/await server\.listen\(/);
    expect(code).toContain("createProjectServer");
  });

  test("binds 0.0.0.0, not the loopback default", () => {
    // `AgentServer.listen` defaults to loopback deliberately — it has no
    // request auth of its own — so a host that reaches the process from
    // outside has to say so, and a deployment that did not would answer
    // nothing while looking healthy.
    expect(code).toContain('"0.0.0.0"');
  });

  test("resolves its artifacts from the MODULE, not the process", () => {
    // `.aai/` is copied in beside this file; the working directory belongs to
    // the platform.
    expect(code).toContain("import.meta.dirname");
    expect(code).not.toContain("process.cwd()");
  });

  test("reaches Deno's env through globalThis", () => {
    // This file is bundled by a Node-side build and read by Node tooling —
    // this spec included — where a bare `Deno` is a ReferenceError.
    expect(code).toContain("globalThis.Deno?.env");
  });

  test("DRAINS on a signal, exactly as the Modal entry does", () => {
    // Deno Deploy stops a deployment on the same events Modal stops a
    // container on — a scale-in, a redeploy — and this entry used to have no
    // handler at all, so a live call lost its socket rather than its session.
    // Nitro has no such asymmetry: every long-lived preset it ships serves
    // through srvx, which closes on SIGINT/SIGTERM.
    expect(code).toMatch(/\["SIGINT", "SIGTERM"\]/);
    expect(code).toContain("server.close()");
  });

  test("says it is generated, since it lands in a user's project", () => {
    expect(DENO_ENTRY_SOURCE).toMatch(/Generated by/);
    expect(DENO_ENTRY_SOURCE).toMatch(/do not edit/i);
  });
});
