// Copyright 2026 the AAI authors. MIT license.
/**
 * The generated `app.py`.
 *
 * This is the only target whose emit writes code in a language nothing in this
 * repo's pipeline compiles — `tsc` cannot see it, Biome does not lint it, and
 * the first thing that evaluates it is `modal deploy` on a user's machine. So
 * the assertions here are deliberately about the file's CLAIMS rather than its
 * formatting, and a real `python3` parse plus an import against the real
 * `modal` library live in `_modal-output.scenario.test.ts`.
 *
 * Each case below is a property whose violation is a deployment that builds
 * and then misbehaves in a way no build output would have hinted at.
 */

import { describe, expect, test } from "vitest";
import {
  MODAL_ENV_KNOBS,
  modalAppName,
  modalAppSource,
  modalNodeImageTag,
  modalSecretName,
} from "./_modal-app.ts";
import { MODAL_APP_FILE, MODAL_ENTRY_FILE, MODAL_PORT } from "./_modal-target.ts";

describe("modalAppName", () => {
  test("free-text agent names become legal hostname labels", () => {
    // An agent name is free text and the app name reaches a hostname
    // (`<workspace>--<app>-<function>.modal.run`), so this is a mapping rather
    // than a validation — refusing the name would refuse a legal agent.
    expect(modalAppName("Retail Support Bot")).toBe("retail-support-bot");
    expect(modalAppName("my_agent.v2")).toBe("my-agent-v2");
    expect(modalAppName("Ünïcödé Agent")).toBe("n-c-d-agent");
  });

  test("no leading, trailing or doubled dash survives", () => {
    // `--` is the workspace separator a hostname reader sees, and a label may
    // not begin or end with a dash.
    expect(modalAppName("  spaced  out  ")).toBe("spaced-out");
    expect(modalAppName("--edgy--")).toBe("edgy");
    expect(modalAppName("a  ---  b")).toBe("a-b");
  });

  test("a name with nothing usable in it still yields a deployable app", () => {
    // The alternative is `modal.App("")`, which fails at deploy time with
    // nothing pointing back at the agent's name as the cause.
    expect(modalAppName("!!!")).toBe("aai-agent");
    expect(modalAppName("")).toBe("aai-agent");
  });

  test("a long name is truncated without leaving a trailing dash", () => {
    // Modal caps a resource name at 64 characters. The truncation can land on
    // a dash, which is why the trim runs after the slice and not only before.
    const long = modalAppName(`${"word ".repeat(40)}tail`);
    expect(long.length).toBeLessThanOrEqual(64);
    expect(long.endsWith("-")).toBe(false);
    expect(long.startsWith("word-word")).toBe(true);
  });
});

describe("modalSecretName", () => {
  test("names the app it belongs to, and says it holds env", () => {
    expect(modalSecretName("my-agent")).toBe("my-agent-env");
  });

  test("stays inside the name cap even for a maximal app name", () => {
    expect(modalSecretName("a".repeat(64)).length).toBeLessThanOrEqual(64);
  });
});

describe("modalNodeImageTag", () => {
  test("tracks the Node the bundle was built with", () => {
    // Modal pulls any tag that exists, so there is nothing to clamp from above
    // — unlike Vercel, whose platform publishes a fixed list.
    expect(modalNodeImageTag("26.1.0")).toBe("node:26-slim");
    expect(modalNodeImageTag("24.15.0")).toBe("node:24-slim");
  });

  test("never emits an image the SDK cannot run in", () => {
    // npm does not enforce `engines` by default, so a build on Node 22 is
    // reachable — and `node:22-slim` would crash-loop rather than fail here.
    expect(modalNodeImageTag("22.14.0")).toBe("node:24-slim");
    expect(modalNodeImageTag("garbage")).toBe("node:24-slim");
  });
});

describe("the generated app.py", () => {
  const source = modalAppSource({ name: "Retail Support Bot" });

  /**
   * The file's CODE — its `#` comments and its module docstring removed.
   *
   * A negative assertion has to read this rather than `source`, because this
   * file explains the anti-patterns it avoids: an `add_local_dir(".")` named in
   * a comment as the thing NOT to do was read by the first draft of that spec
   * as the thing being done. Same trap the Vercel entry's spec documents, one
   * language over.
   */
  const code = (() => {
    const lines = source.split("\n").filter((line) => !line.trimStart().startsWith("#"));
    const open = lines.findIndex((line) => line.startsWith('"""'));
    const close = lines.findIndex((line, i) => i > open && line.startsWith('"""'));
    return (open === -1 ? lines : [...lines.slice(0, open), ...lines.slice(close + 1)]).join("\n");
  })();

  test("says it is generated, since it lands in a user's project", () => {
    expect(source).toMatch(/Generated by/);
    expect(source).toMatch(/do not edit/i);
  });

  test("routes to the SAME port the node entry binds", () => {
    // The failure this prevents is the quietest one available: the proxy routes
    // to the port it was told about, so a mismatch is a deployment that builds,
    // starts, reports healthy and answers nothing.
    expect(source).toContain(`PORT = ${MODAL_PORT}`);
    expect(source).toContain("@modal.web_server(port=PORT");
    expect(source).toContain('.env({"NODE_ENV": "production", "PORT": str(PORT)})');
    // One literal, so the three uses above cannot drift apart.
    expect(source.match(new RegExp(`\\b${MODAL_PORT}\\b`, "g"))).toHaveLength(1);
  });

  test("declares concurrency, without which one call blocks the container", () => {
    // Modal serves ONE input per container by default and a WebSocket is one
    // input for the life of the call: the second caller would wait out the
    // first, and every asset request for the client would queue behind whatever
    // call is in progress. This is the single most consequential line here.
    expect(source).toMatch(/@modal\.concurrent\(max_inputs=\d+, target_inputs=\d+\)/);
    const [, max, target] = source.match(/max_inputs=(\d+), target_inputs=(\d+)/) ?? [];
    // The set point has to sit UNDER the cap, or scale-out never precedes
    // saturation and the knob does nothing.
    expect(Number(target)).toBeLessThan(Number(max));
  });

  test("spawns the entry the emit actually writes", () => {
    expect(source).toContain(`ENTRY = "${MODAL_ENTRY_FILE}"`);
    expect(source).toContain("_run_node(ENTRY, env)");
  });

  test("hands container stop signals to node rather than spawning a bare Popen", () => {
    // Modal signals its own Python runtime; a bare `Popen` child receives
    // nothing, so node's shutdown — the thing that closes live voice sessions —
    // would never run on a scale-in or a redeploy. The platform's own deploy
    // learned this by billing orphaned sandboxes on every release.
    expect(source).toContain("proc.send_signal(signal.SIGTERM)");
    expect(source).toContain("atexit.register(stop)");
    // Both hooks: `signal.signal` only works on the main thread and Modal may
    // call the function off it, so neither alone is reliable.
    expect(source).toMatch(/for signum in \(signal\.SIGTERM, signal\.SIGINT\)/);
  });

  test("uploads its OWN directory, never the shell's", () => {
    // `modal deploy` resolves a relative local path against the directory it
    // was invoked from, so `add_local_dir(".")` would bake the project root —
    // node_modules, source and the developer's `.env` — into an image layer.
    expect(code).toContain("HERE = Path(__file__).parent");
    expect(code).toMatch(/add_local_dir\(\s*HERE,/);
    expect(code).not.toMatch(/add_local_dir\(\s*["'.]/);
  });

  test("copies into a layer rather than mounting at container start", () => {
    // A runtime mount re-uploads the browser client on every cold start.
    expect(source).toContain("copy=True");
  });

  test("takes its env from a Secret, and fails the deploy when it is missing", () => {
    // The alternative is a container that starts and has no provider
    // credential. `.env.example` beside it declares WHICH names reach ctx.env.
    expect(source).toContain("modal.Secret.from_name(SECRET_NAME)");
    expect(source).toContain("retail-support-bot-env");
  });

  test("strips MODAL_SERVER_URL before node inherits the environment", () => {
    // Modal points it at an in-container Unix socket for its own Python task
    // runtime; the `modal` JS SDK prefers it over the public endpoint and would
    // dial a socket that does not answer.
    expect(source).toContain('env.pop("MODAL_SERVER_URL", None)');
  });

  test("every documented knob is one the file really reads", () => {
    // The docstring is where a user learns these exist, so a knob named there
    // and read nowhere is a documented no-op — and one read but undocumented is
    // unreachable in practice.
    for (const knob of MODAL_ENV_KNOBS) {
      expect(source).toContain(`os.environ.get("${knob}"`);
      expect(source).toContain(`    ${knob} `);
    }
    const read = source.match(/os\.environ\.get\("(AAI_MODAL_[A-Z_]+)"/g) ?? [];
    expect(read).toHaveLength(MODAL_ENV_KNOBS.length);
  });

  test("names itself the way the emit writes it", () => {
    // The docstring carries the `modal deploy` command a user copies, so it has
    // to name the path the emit actually produces.
    expect(source).toContain(`modal deploy .aai/modal/${MODAL_APP_FILE}`);
  });

  test("the app name is overridable but defaults to the agent's", () => {
    expect(source).toContain('os.environ.get("AAI_MODAL_APP", "retail-support-bot")');
    expect(source).toContain("app = modal.App(APP_NAME)");
  });

  test("a caller may pin the base image", () => {
    const pinned = modalAppSource({ name: "a", nodeImage: "node:99-slim" });
    expect(pinned).toContain('from_registry("node:99-slim"');
  });
});
