// Copyright 2026 the AAI authors. MIT license.
/**
 * The Modal target's emitted node entry — the half `app.py` spawns.
 *
 * `_modal-app.test.ts` covers the Python beside it; what is asserted here is
 * the contract BETWEEN the two, above all the port they have to agree on.
 */

import { describe, expect, test } from "vitest";
import { MODAL_ENTRY_SOURCE, MODAL_PORT } from "./_modal-target.ts";

describe("the emitted Modal entry", () => {
  const code = MODAL_ENTRY_SOURCE.split("\n")
    .filter((line) => !line.trimStart().startsWith("//"))
    .join("\n");

  test("BINDS, like Deno's and unlike Vercel's", () => {
    // `@modal.web_server` runs a container command and proxies to a port that
    // command opens, so this is the long-lived `aai start` shape.
    expect(code).toMatch(/await server\.listen\(/);
    expect(code).toContain("createProjectServer");
  });

  test("binds 0.0.0.0, not the loopback default", () => {
    // Modal's proxy reaches this from outside the process, so a loopback bind
    // answers nothing while the container looks healthy.
    expect(code).toContain('"0.0.0.0"');
  });

  test("reads the port app.py routes to, from the environment app.py sets", () => {
    // The image bakes PORT and the decorator routes to it. The literal here is
    // the fallback for a container started without it.
    expect(code).toContain("process.env.PORT");
    expect(code).toContain(String(MODAL_PORT));
    // Node's own env, not Deno's — this entry is never bundled for Deploy.
    expect(code).not.toContain("globalThis.Deno");
  });

  test("resolves its artifacts from the MODULE, not the process", () => {
    // `.aai/` is copied in beside this file; the working directory belongs to
    // the platform.
    expect(code).toContain("import.meta.dirname");
    expect(code).not.toContain("process.cwd()");
  });

  test("DRAINS on a signal, and app.py is what makes the signal arrive", () => {
    // Modal stops a container on every scale-in and every redeploy, which for
    // a voice agent is a live call being cut. `close()` shuts the runtime down
    // with it, so sessions end rather than sockets dropping. app.py forwards
    // the signal and waits; this is the half that acts on it.
    expect(code).toMatch(/\["SIGINT", "SIGTERM"\]/);
    expect(code).toContain("server.close()");
    // Synchronous, for the reason `executeStart` documents: an async listener
    // hands its promise to `process`, which discards it, so a failed shutdown
    // would surface as an unhandled rejection instead of a non-zero exit.
    expect(code).not.toMatch(/process\.once\([^)]*async/);
  });

  test("says it is generated, since it lands in a user's project", () => {
    expect(MODAL_ENTRY_SOURCE).toMatch(/Generated by/);
    expect(MODAL_ENTRY_SOURCE).toMatch(/do not edit/i);
  });
});
