// Copyright 2026 the AAI authors. MIT license.
/**
 * The **Modal** target — a self-contained directory under `.aai/modal/`, plus
 * the `app.py` that deploys it.
 *
 * One module per host, for the reason `_vercel-target.ts` opens with. This file
 * holds where the directory goes and the node entry inside it; `_modal-app.ts`
 * generates the Python module beside it, and `_modal-output.ts` assembles both.
 *
 * The long-lived half of the pair described in `_deno-target.ts`.
 */

import path from "node:path";
import { TARGET_DRAIN_SOURCE } from "./_target-drain.ts";

/**
 * Where a self-contained Modal deployment is emitted, relative to the project.
 *
 * A directory, for the reason `_deno-target.ts`'s `DENO_OUTPUT_DIR` is one and
 * then some: the
 * emitted `app.py` hands this path to Modal's `add_local_dir`, which uploads
 * the tree wholesale into the image. Pointed at the project root that would
 * bake `node_modules`, the source and the developer's `.env` into a container
 * image — and an image layer is not something you can un-push.
 */
export const MODAL_OUTPUT_DIR = path.join(".aai", "modal");

/** The bundled server inside {@link MODAL_OUTPUT_DIR}, spawned by `app.py`. */
export const MODAL_ENTRY_FILE = "server.mjs";

/** The Modal app definition inside {@link MODAL_OUTPUT_DIR} — what `modal deploy` reads. */
export const MODAL_APP_FILE = "app.py";

/**
 * The port the node process binds and Modal proxies to.
 *
 * ONE constant, interpolated into both files the emit writes, because the two
 * halves cannot be allowed to disagree: `@modal.web_server(port=…)` is how the
 * platform learns where to route, and a node process reading a different number
 * from its environment listens where nothing is routed. The symptom is a
 * deployment that builds, starts, reports healthy, and answers no request —
 * Modal's proxy simply never connects.
 */
export const MODAL_PORT = 8000;

/**
 * The Modal entry, bundled into {@link MODAL_ENTRY_FILE}.
 *
 * ## The same binding shape as Deno, for a different host
 *
 * `@modal.web_server` runs a container command and proxies HTTP *and*
 * WebSocket traffic to a port that command opens, so this is the long-lived
 * `aai start` shape rather than the serverless one — `listen()`, `0.0.0.0`
 * (the proxy reaches this from outside the process), and artifacts resolved
 * from {@link MODAL_ENTRY_FILE}'s own directory rather than from a working
 * directory the platform owns. The entry is still NOT shared with
 * {@link DENO_ENTRY_SOURCE} — the two read the port from different runtimes,
 * and a shared entry would be a template with a hole where that goes — but the
 * DRAIN below is, which is the part neither host's contract varies in.
 *
 * ## The drain is SHARED, and Modal supplies its other half
 *
 * The `SIGINT`/`SIGTERM` body is {@link TARGET_DRAIN_SOURCE}, the same text the
 * Deno entry carries — it used to live here alone, on the reading that Modal
 * stops containers and Deno Deploy does not, which is not true of either.
 *
 * What IS specific to Modal is that the signal has to REACH this process at
 * all, and that half is in `app.py`: Modal signals its own Python runtime, and
 * a child spawned with a bare `subprocess.Popen` receives nothing. The
 * platform's own deploy learned that when orphaned guest sandboxes billed ~20
 * minutes each on every release (see `run_node` in `scripts/modal_image.py`).
 */
export const MODAL_ENTRY_SOURCE = `// Generated by \`aai build --target modal\` — do not edit, and do not commit.
// Modal runs this as a long-lived process behind \`@modal.web_server\`, which
// proxies HTTP and WebSocket traffic to the port it binds.
// See @alexkroman1/aai-cli/start.
import { createProjectServer } from "@alexkroman1/aai-cli/start";

const server = await createProjectServer({ cwd: import.meta.dirname });

await server.listen(Number(process.env.PORT ?? ${MODAL_PORT}), "0.0.0.0");

// app.py forwards the container's stop signal here and waits for this process.
${TARGET_DRAIN_SOURCE}`;
