// Copyright 2026 the AAI authors. MIT license.
/**
 * The long-lived entry every self-contained target emits.
 *
 * The two host specs beside this one (`_deno-target.test.ts`,
 * `_modal-target.test.ts`) assert what their host adds. What is asserted here
 * is the half they SHARE, and above all the property that makes sharing worth
 * anything: the emitted artifact is not pinned to the runtime whose host
 * emitted it.
 *
 * That property is also what licenses `_target-runtimes.scenario.test.ts` to
 * boot a SYNTHETIC emit under all three runtimes and call the result a fact
 * about both real targets — so the "differ only in the banner and the port"
 * case below is load-bearing rather than tidy.
 */

import { describe, expect, test } from "vitest";
import { DENO_ENTRY_SOURCE, DENO_PORT } from "./_deno-target.ts";
import { MODAL_ENTRY_SOURCE, MODAL_PORT } from "./_modal-target.ts";
import { longLivedEntrySource, RUNTIME_PORT_SOURCE } from "./_target-entry.ts";

/** The code with comments stripped, so a claim cannot be satisfied by prose. */
const stripped = (source: string): string =>
  source
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("//"))
    .join("\n");

describe("longLivedEntrySource", () => {
  const code = stripped(
    longLivedEntrySource({
      target: "probe",
      hostNote: ["A host note."],
      defaultPort: 4242,
    }),
  );

  test("reads the port from whichever runtime it is running in", () => {
    // The whole portability claim, in one expression. Deno's env first and
    // Node's second, and both present: each of the two real entries used to
    // read exactly one of them, which pinned each emitted directory to one
    // runtime for no reason anybody had decided (see the module doc).
    expect(code).toContain(RUNTIME_PORT_SOURCE);
    expect(code).toContain("globalThis.Deno?.env");
    expect(code).toContain("process.env.PORT");
    expect(code).toContain("4242");
  });

  test("binds, on every interface, and resolves artifacts beside itself", () => {
    // A long-lived host runs a process and expects it to listen — the Vercel
    // entry, which is a `(req, res)` handler, must NOT do this. `0.0.0.0`
    // because every host here reaches the process from outside it, and a
    // loopback bind answers nothing while looking healthy. And
    // `import.meta.dirname` because `.aai/` is copied in beside the entry
    // while the working directory belongs to the platform.
    expect(code).toMatch(/await server\.listen\(/);
    expect(code).toContain('"0.0.0.0"');
    expect(code).toContain("import.meta.dirname");
    expect(code).not.toContain("process.cwd()");
  });

  test("drains on a signal, synchronously", () => {
    // A host stops this process on every scale-in and every redeploy, which
    // for a voice agent is a live call. The listener is synchronous for the
    // reason `executeStart` documents: an async one hands its promise to
    // `process`, which discards it, so a failed shutdown would surface as an
    // unhandled rejection instead of the non-zero exit it should be.
    expect(code).toMatch(/\["SIGINT", "SIGTERM"\]/);
    expect(code).toContain("server.close()");
    expect(code).not.toMatch(/process\.once\([^)]*async/);
  });

  test("says it is generated, and names the flag that generated it", () => {
    // It lands in a user's project, so it has to say both — a file that says
    // "do not edit" without naming the command that rewrites it leaves the
    // reader nothing to do.
    const source = longLivedEntrySource({ target: "probe", hostNote: [], defaultPort: 1 });
    expect(source).toMatch(/Generated by `aai build --target probe`/);
    expect(source).toMatch(/do not edit/i);
  });
});

describe("the two long-lived targets", () => {
  test("differ only in the banner and the default port", () => {
    // What licenses the scenario matrix's synthetic subject. If a host ever
    // needs a real line of its own the matrix stops covering it, and this is
    // what fails — rather than the runtime arms quietly proving something
    // about a body neither host ships.
    const shared = (source: string, port: number): string =>
      stripped(source).replaceAll(String(port), "<PORT>");
    expect(shared(DENO_ENTRY_SOURCE, DENO_PORT)).toBe(shared(MODAL_ENTRY_SOURCE, MODAL_PORT));
  });

  test("default to the same port, so a reader who ran one emit knows the other", () => {
    expect(DENO_PORT).toBe(MODAL_PORT);
  });
});
