// Copyright 2026 the AAI authors. MIT license.
/**
 * The LONG-LIVED entry — one source, and every runtime that can run it.
 *
 * A leaf beside `_target-drain.ts` (the signal handler both long-lived entries
 * carry), `_target-output.ts` (the directory they share) and
 * `_target-bundle.ts` (the bundle every target's entry goes through): each is a
 * thing more than one host needs and no host owns.
 *
 * ## Why the entry is shared, when it deliberately was not
 *
 * Both long-lived entries do the same four things — build the server, bind a
 * port, bind it on `0.0.0.0`, drain on a signal — and the argument for keeping
 * two copies was the port: `MODAL_ENTRY_SOURCE`'s own doc records it as "the
 * two read the port from different runtimes, and a shared entry would be a
 * template with a hole where that goes".
 *
 * That is true only if a runtime's env is read one runtime's way. It was: the
 * Deno entry read `globalThis.Deno?.env.get("PORT")` and nothing else, and the
 * Modal entry read `process.env.PORT` and nothing else — so each emitted
 * artifact was pinned to its host by ONE expression, and running the Deno
 * directory under `node` or `bun` bound the default port no matter what the
 * host had set. Nobody decided that; it fell out of which global was in reach
 * when each file was written.
 *
 * {@link RUNTIME_PORT_SOURCE} reads BOTH, so the artifact is portable and the
 * hole in the template closes. What is left per host is a comment and a
 * default, which is what {@link longLivedEntrySource} takes.
 *
 * ## Why portability is a property worth spending a module on
 *
 * A self-contained emit is a directory with no `node_modules`, no toolchain and
 * one file to run — which is exactly what a container image carries, and the
 * runtime in that image is the operator's choice, not ours. `deno`, `node` and
 * `bun` all run this file; `_target-runtimes.scenario.test.ts` boots the emit
 * under each of the three and dials a real session on it, because nothing else
 * here can tell you that the same bundle serves on all three rather than only
 * on the one host whose target emitted it.
 */

import { TARGET_DRAIN_SOURCE } from "./_target-drain.ts";

/**
 * The port expression every long-lived entry uses, reading whichever runtime
 * it finds itself in.
 *
 * `globalThis.Deno?.env` rather than `Deno.env`, and the optional chain is
 * load-bearing twice over: this file is bundled by a Node-side build and read
 * by Node tooling (its own specs included), where a bare `Deno` is a
 * `ReferenceError` — and under Node and Bun the chain is what falls through to
 * `process.env` instead of throwing.
 *
 * `process.env` second rather than first, because Deno's `process` shim reads
 * the same variables and asking Deno for them Deno's way is what keeps the
 * Deno arm honest — a host that grants no env permission fails on the first
 * read either way.
 *
 * `process` itself needs no guard and deliberately gets none: it is a global in
 * all three runtimes, which is what lets {@link TARGET_DRAIN_SOURCE} be the
 * identical text in every entry rather than a template with a hole in it.
 */
export const RUNTIME_PORT_SOURCE = 'globalThis.Deno?.env.get("PORT") ?? process.env.PORT';

/** What one host varies in the entry it emits. */
export interface LongLivedEntry {
  /** The `--target` name, for the "do not edit" banner a user's project shows. */
  readonly target: string;
  /** Why this host runs a long-lived process, as comment lines above the code. */
  readonly hostNote: readonly string[];
  /** The port to bind when the host set none. */
  readonly defaultPort: number;
  /** A comment above the drain, where the host supplies the signal's other half. */
  readonly drainNote?: string;
}

/**
 * The entry a long-lived host runs, bundled into that target's entry file.
 *
 * `0.0.0.0`, not `AgentServer.listen`'s loopback default: every host here
 * reaches the process from outside it, so a loopback bind answers nothing while
 * looking healthy.
 *
 * `import.meta.dirname` rather than `process.cwd()`: the artifacts are copied
 * in BESIDE this file (see `_target-output.ts`) and the working directory
 * belongs to the platform.
 */
export function longLivedEntrySource(entry: LongLivedEntry): string {
  const note = entry.hostNote.map((line) => `// ${line}\n`).join("");
  const drainNote = entry.drainNote === undefined ? "" : `// ${entry.drainNote}\n`;
  return `// Generated by \`aai build --target ${entry.target}\` — do not edit, and do not commit.
${note}// See @alexkroman1/aai-cli/start.
import { createProjectServer } from "@alexkroman1/aai-cli/start";

const server = await createProjectServer({ cwd: import.meta.dirname });

await server.listen(Number(${RUNTIME_PORT_SOURCE} ?? ${entry.defaultPort}), "0.0.0.0");

${drainNote}${TARGET_DRAIN_SOURCE}`;
}
