// Copyright 2026 the AAI authors. MIT license.
/**
 * The Vercel target's emitted sources — the function entry, its `.vc-config`,
 * and the Build Output API routing table.
 *
 * Every case here asserts a property that only a DEPLOYMENT could otherwise
 * report: a handler shape the launcher does not invoke, a function directory
 * whose name a static file can claim, an asset served with the wrong freshness.
 * The suite exists because that feedback loop is minutes long and lossy.
 */

import { describe, expect, test } from "vitest";
import {
  VERCEL_BUILD_CONFIG_SOURCE,
  VERCEL_ENTRY_SOURCE,
  VERCEL_FUNCTION_DIR,
  VERCEL_FUNCTION_ROUTE,
  vercelFunctionConfigSource,
  vercelNodeRuntime,
} from "./_vercel-target.ts";

describe("the emitted Vercel entry", () => {
  const code = VERCEL_ENTRY_SOURCE.split("\n")
    .filter((line) => !line.trimStart().startsWith("//"))
    .join("\n");

  test("default-exports a request HANDLER, and never calls listen", () => {
    // The Build Output API has no builder in the path: `launcherType: "Nodejs"`
    // invokes the default export per request. An `http.Server` there is never
    // bound and serves nothing — which is why this is not the `export default
    // server` shape `@vercel/node` accepts.
    expect(code).toMatch(/export default function handler\(req, res\)/);
    // Comments are stripped above: the file explains that it does not call
    // listen(), so a naive match reads its own explanation as the thing.
    expect(code).not.toMatch(/\blisten\s*\(/);
    // Through the published subpath, not a relative path: this file is bundled
    // from inside a user's project, where `./start.ts` means nothing.
    expect(VERCEL_ENTRY_SOURCE).toContain('from "@alexkroman1/aai-cli/start"');
  });

  test("a WebSocket upgrade is re-emitted onto the server, not handled here", () => {
    // Vercel delivers the raw upgrade through its per-request context rather
    // than as an event. Everything downstream — auth, the session, /phone — is
    // registered on the `http.Server`'s own `upgrade` listener, so translating
    // must end in an `emit` and never in a second WebSocket implementation
    // that would drift from the one `aai dev` and `aai start` run.
    expect(code).toContain('Symbol.for("@vercel/request-context")');
    expect(code).toMatch(/upgradeWebSocket\?\.\(\)/);
    expect(code).toMatch(/server\.emit\("upgrade", upgrade\.req, upgrade\.socket, upgrade\.head\)/);
    expect(code).toMatch(/server\.emit\("request", req, res\)/);
  });

  test("a non-upgrade request is never answered with the 204", () => {
    // The 204 ends the INVOCATION once the socket has been handed off; the
    // agent talks on `upgrade.socket`, not on this `res`. Emitting it on an
    // ordinary request would answer every page load with an empty body.
    const upgradeArm = code.slice(
      code.indexOf("if (upgrade)"),
      code.indexOf('server.emit("request"'),
    );
    expect(upgradeArm).toContain("res.statusCode = 204");
    expect(code.slice(code.indexOf('server.emit("request"'))).not.toContain("204");
  });

  test("says it is generated, since it lands in a user's project", () => {
    expect(VERCEL_ENTRY_SOURCE).toMatch(/Generated by/);
    expect(VERCEL_ENTRY_SOURCE).toMatch(/do not edit/i);
  });
});

describe("the emitted Build Output API config", () => {
  test("static files are served before anything reaches the function", () => {
    const config = JSON.parse(VERCEL_BUILD_CONFIG_SOURCE) as {
      version: number;
      routes: {
        handle?: string;
        src?: string;
        dest?: string;
        status?: number;
        continue?: boolean;
        headers?: Record<string, string>;
      }[];
    };
    expect(config.version).toBe(3);
    // Order is the whole meaning of this table: `handle: filesystem` in the
    // middle is what lets the CDN answer for the client bundle, and the
    // catch-all last is what keeps /client-config, /websocket, /workflows/* and
    // the webhook route reaching the agent. Reversed, every asset costs an
    // invocation. The two rules bracketing `filesystem` are Nitro's shape and
    // are asserted for their own properties below.
    expect(config.routes.map((r) => r.handle ?? r.src)).toEqual([
      "/assets/(.*)",
      "filesystem",
      "/assets/(.*)",
      "/(.*)",
    ]);
    expect(config.routes.at(-1)).toEqual({ src: "/(.*)", dest: VERCEL_FUNCTION_ROUTE });
  });

  test("hashed assets are cached forever, and the rule CONTINUES", () => {
    const config = JSON.parse(VERCEL_BUILD_CONFIG_SOURCE) as {
      routes: { src?: string; continue?: boolean; headers?: Record<string, string> }[];
    };
    const [header] = config.routes;
    // A filename that changes with its bytes can be cached forever. Without
    // this the CDN serves the bundle on Vercel's default freshness and every
    // client re-validates every asset on every load.
    expect(header?.headers?.["cache-control"]).toBe("public, max-age=31536000, immutable");
    // `continue: true` is what keeps this a HEADER rule: the request goes on to
    // `filesystem` and is served there. Terminal, it would answer every asset
    // with an empty 200.
    expect(header?.continue).toBe(true);
  });

  test("a MISS under the hashed prefix 404s at the CDN, uncached", () => {
    const config = JSON.parse(VERCEL_BUILD_CONFIG_SOURCE) as {
      routes: {
        src?: string;
        status?: number;
        continue?: boolean;
        headers?: Record<string, string>;
      }[];
    };
    const missAt = config.routes.findIndex((r) => r.status === 404);
    const miss = config.routes[missAt];
    // A miss under a content-hashed name is a stale index.html asking for a
    // bundle this deployment does not have — there is no version of that
    // request the agent can answer, so falling through buys an invocation to
    // produce the 404 the CDN already could.
    expect(miss?.src).toBe("/assets/(.*)");
    expect(miss?.continue).toBe(false);
    // And it must take the immutable header back: that header is already
    // attached by the rule above, so a dynamic 404 inheriting it would be
    // cached for a year.
    expect(miss?.headers?.["cache-control"]).toBe("no-store");
    // Ordering is the whole mechanism — the 404 has to come AFTER the
    // filesystem handle, or nothing under the prefix is ever served.
    const handleAt = config.routes.findIndex((r) => "handle" in r);
    expect(missAt).toBeGreaterThan(handleAt);
  });

  test("the function's route cannot be claimed by a static file", () => {
    // The Build Output API derives the route from the directory name, so the
    // name is a URL. `index.func` served at `/index` took `/` from the static
    // index.html on a real preview deployment — every other asset was fine and
    // the home page 500'd. A `__` prefix is not a path any bundler emits.
    expect(VERCEL_FUNCTION_DIR.endsWith(`${VERCEL_FUNCTION_ROUTE.slice(1)}.func`)).toBe(true);
    expect(VERCEL_FUNCTION_ROUTE).toMatch(/^\/__/);
  });

  test("the function config names the entry and keeps streaming on", () => {
    const config = JSON.parse(vercelFunctionConfigSource("nodejs22.x")) as Record<string, unknown>;
    expect(config.handler).toBe("index.mjs");
    expect(config.launcherType).toBe("Nodejs");
    expect(config.runtime).toBe("nodejs22.x");
    // An agent streams TTS audio and SSE workflow events. Buffered to
    // completion, a stream that ends when the call does never arrives.
    expect(config.supportsResponseStreaming).toBe(true);
  });

  test("the runtime is the smallest offered major that is at least this one", () => {
    // Exact matches are themselves.
    expect(vercelNodeRuntime("22.14.0")).toBe("nodejs22.x");
    // Rounds UP, and this is the case that used to round down. The bundle in
    // the function resolved its dependencies for the Node that built it, so
    // running it on an OLDER major turns an API that shipped in 23 into a
    // runtime TypeError in a function that built clean. Nitro's
    // `resolveVercelRuntime` picks the same direction over the same list.
    expect(vercelNodeRuntime("23.1.0")).toBe("nodejs24.x");
    expect(vercelNodeRuntime("21.0.0")).toBe("nodejs22.x");
    // Above the list there is nothing to round up to, so it clamps rather than
    // naming a runtime the deployment would be rejected for.
    expect(vercelNodeRuntime("26.0.0")).toBe("nodejs24.x");
    // Below it, the oldest offered — the same answer either direction gives.
    expect(vercelNodeRuntime("18.20.0")).toBe("nodejs20.x");
    // An unparsable version still has to name something.
    expect(vercelNodeRuntime("not-a-version")).toBe("nodejs22.x");
  });
});
