/**
 * The word list — their `word_list.py`, trimmed to twenty of each of its eleven
 * categories (the original carries about sixty). Words a describer can get across
 * in a sentence or two: a game clock of two minutes wants words the AI player can
 * reach, not ones that need a lecture.
 *
 * `pickWords` is their `generate_game_words`: flatten, dedupe, sample.
 */

export const WORD_CATEGORIES = {
  animals: [
    "elephant",
    "penguin",
    "giraffe",
    "dolphin",
    "kangaroo",
    "octopus",
    "panda",
    "tiger",
    "koala",
    "flamingo",
    "hedgehog",
    "turtle",
    "zebra",
    "eagle",
    "sloth",
    "raccoon",
    "chameleon",
    "squirrel",
    "hamster",
    "cheetah",
  ],
  food: [
    "pizza",
    "sushi",
    "burrito",
    "pancake",
    "donut",
    "lasagna",
    "popcorn",
    "chocolate",
    "mango",
    "pretzel",
    "taco",
    "waffle",
    "cupcake",
    "avocado",
    "cookie",
    "croissant",
    "omelette",
    "cheesecake",
    "dumpling",
    "hummus",
  ],
  household: [
    "chair",
    "pillow",
    "mirror",
    "blanket",
    "lamp",
    "curtain",
    "sofa",
    "refrigerator",
    "blender",
    "bookshelf",
    "dishwasher",
    "carpet",
    "microwave",
    "table",
    "clock",
    "vase",
    "ottoman",
    "candle",
    "drawer",
    "cabinet",
  ],
  activities: [
    "swimming",
    "painting",
    "dancing",
    "gardening",
    "skiing",
    "cooking",
    "hiking",
    "reading",
    "yoga",
    "fishing",
    "jogging",
    "biking",
    "baking",
    "singing",
    "camping",
    "knitting",
    "surfing",
    "photography",
    "bowling",
    "archery",
  ],
  places: [
    "beach",
    "library",
    "mountain",
    "airport",
    "stadium",
    "museum",
    "hospital",
    "castle",
    "garden",
    "hotel",
    "island",
    "desert",
    "university",
    "restaurant",
    "forest",
    "aquarium",
    "theater",
    "canyon",
    "lighthouse",
    "waterfall",
  ],
  objects: [
    "umbrella",
    "scissors",
    "camera",
    "wallet",
    "bicycle",
    "backpack",
    "telescope",
    "balloon",
    "compass",
    "notebook",
    "keyboard",
    "magnet",
    "headphones",
    "hammer",
    "envelope",
    "binoculars",
    "tambourine",
    "boomerang",
    "megaphone",
    "suitcase",
  ],
  jobs: [
    "teacher",
    "doctor",
    "chef",
    "firefighter",
    "pilot",
    "astronaut",
    "carpenter",
    "musician",
    "detective",
    "scientist",
    "farmer",
    "architect",
    "journalist",
    "electrician",
    "dentist",
    "veterinarian",
    "librarian",
    "photographer",
    "mechanic",
    "attorney",
  ],
  transportation: [
    "helicopter",
    "submarine",
    "scooter",
    "sailboat",
    "train",
    "motorcycle",
    "airplane",
    "canoe",
    "tractor",
    "limousine",
    "escalator",
    "skateboard",
    "ambulance",
    "ferry",
    "rocket",
    "hovercraft",
    "gondola",
    "segway",
    "zeppelin",
    "bulldozer",
  ],
  clothing: [
    "sweater",
    "sandals",
    "tuxedo",
    "poncho",
    "sneakers",
    "bikini",
    "cardigan",
    "overalls",
    "kimono",
    "mittens",
    "suspenders",
    "kilt",
    "leggings",
    "apron",
    "bowtie",
    "earmuffs",
    "fedora",
    "wetsuit",
    "pajamas",
    "sombrero",
  ],
  nature: [
    "glacier",
    "sequoia",
    "geyser",
    "avalanche",
    "tornado",
    "quicksand",
    "stalactite",
    "hurricane",
    "asteroid",
    "tundra",
    "galaxy",
    "nebula",
    "earthquake",
    "stalagmite",
    "constellation",
    "crystal",
    "tributary",
    "abyss",
    "monsoon",
    "magma",
  ],
  emotions: [
    "happiness",
    "sadness",
    "anxiety",
    "surprise",
    "anger",
    "curiosity",
    "embarrassment",
    "nostalgia",
    "envy",
    "gratitude",
    "remorse",
    "boredom",
    "excitement",
    "loneliness",
    "pride",
    "jealousy",
    "contentment",
    "disgust",
    "empathy",
    "euphoria",
  ],
} as const;

/** Every word, once, whatever category it came from. */
export function allWords(): string[] {
  return [...new Set(Object.values(WORD_CATEGORIES).flat())];
}

/**
 * A round's words: `count` of them, sampled without replacement.
 *
 * `random` is a parameter so a spec can hand in a fixed sequence and know
 * which word is up; the tools pass `Math.random`.
 */
export function pickWords(count: number, random: () => number = Math.random): string[] {
  const pool = allWords();
  // Fisher-Yates over the prefix we need, which is what `random.sample` does.
  for (let i = 0; i < Math.min(count, pool.length); i++) {
    const j = i + Math.floor(random() * (pool.length - i));
    [pool[i], pool[j]] = [pool[j] as string, pool[i] as string];
  }
  return pool.slice(0, count);
}
