// Copyright 2026 the AAI authors. MIT license.
/**
 * FROZEN authoring example — `aai:tool`, epoch 3.
 *
 * Epoch 3 is RETAINED, which means this file is a promise: a tool written the
 * way epoch 3 was written must keep compiling. `pnpm typecheck` is what tests
 * that — the compile error is the finding, so do NOT edit this file to make one
 * go away. Either the change that broke it is a break (drop the epoch, and this
 * file goes with it), or the change is wrong.
 *
 * Epoch 4 added `requireEnv`. Nothing was removed, so epoch 3 still stands: the
 * whole point of this file is that reading `ctx.env.X` directly — the only way
 * there was in epoch 3 — remains legal.
 */

import { z } from "zod";
import type { InferToolInput, InferToolOutput, ToolContext, ToolFailure } from "../../../index.ts";
import { isToolFailure, tool, toolFailure } from "../../../index.ts";

/** The shape epoch 3 authored: a Zod object schema, a typed `execute`, a `ToolFailure` return. */
export const lookupNote = tool({
  description: "Look up a saved note by its id",
  inputSchema: z.object({ id: z.string() }),
  async execute({ id }, ctx: ToolContext) {
    // Epoch 3 had no `requireEnv`. A direct read plus a hand-written guard was
    // the idiom, and it stays legal — the `Partial` on `env` only means the
    // guard is now also what the checker asks for.
    const base = ctx.env.NOTES_API;
    if (base === undefined) return toolFailure("NOTES_API is not configured.");
    const res = await fetch(`${base}/notes/${id}`);
    if (!res.ok) return toolFailure(`The notes service answered ${res.status}.`);
    return { id, note: (await res.json()) as unknown };
  },
});

/** The inference helpers epoch 3 published, exercised so a widening shows up here. */
export type LookupInput = InferToolInput<typeof lookupNote>;
export type LookupOutput = InferToolOutput<typeof lookupNote>;

/** `isToolFailure` narrowing, the epoch-3 way to read a tool result back. */
export function describe(result: LookupOutput | ToolFailure): string {
  return isToolFailure(result) ? `failed: ${result.error}` : "ok";
}
