// Copyright 2026 the AAI authors. MIT license.
/**
 * FROZEN authoring example — `aai:tool`, epoch 4.
 *
 * Epoch 4 is where `requireEnv` landed and where `ToolContext.env` became
 * `Partial`. Epoch 5 changed nothing in this capability's own surface — its
 * hash moved because `ToolContext` regained the doc comment that briefly
 * attached to `requireEnv` instead, while that function still lived in
 * `tool-context.ts`. Epoch 4 is RETAINED, and this is what it looked like.
 *
 * Do not edit this file to make a compile error go away; the error IS the
 * finding.
 */

import { z } from "zod";
import type { InferToolInput, InferToolOutput, ToolContext, ToolFailure } from "../../../index.ts";
import { isToolFailure, requireEnv, tool, toolFailure } from "../../../index.ts";

/** The epoch-4 idiom: `requireEnv` instead of a hand-written presence guard. */
export const lookupNote = tool({
  description: "Look up a saved note by its id",
  inputSchema: z.object({ id: z.string() }),
  async execute({ id }, ctx: ToolContext) {
    const base = requireEnv(ctx, "NOTES_API");
    const res = await fetch(`${base}/notes/${id}`);
    if (!res.ok) return toolFailure(`The notes service answered ${res.status}.`);
    return { id, note: (await res.json()) as unknown };
  },
});

/** Reading the env directly stays legal — `Partial` only asks for the guard. */
export const optionalBase = tool({
  description: "Report which notes service is configured",
  inputSchema: z.object({}),
  execute: (_args, ctx: ToolContext) => ({ base: ctx.env.NOTES_API ?? "unset" }),
});

export type LookupInput = InferToolInput<typeof lookupNote>;
export type LookupOutput = InferToolOutput<typeof lookupNote>;

export function describe(result: LookupOutput | ToolFailure): string {
  return isToolFailure(result) ? `failed: ${result.error}` : "ok";
}
