// Copyright 2026 the AAI authors. MIT license.
/**
 * The three files DERIVED from the per-entry-point API reports.
 *
 * `api-report.mjs` runs API Extractor over every published entry point and
 * writes one `etc/<slug>.api.md` each — that is one job. Turning those reports
 * into the three artifacts a reader uses is another, and it shares nothing with
 * the first but the list of reports:
 *
 * | File | Answers |
 * | --- | --- |
 * | `API.md` | what is the whole surface, in one pass |
 * | `API-EXPORTS.json` | what names are IN each subpath |
 * | `API-INDEX.md` | which subpath publishes a given name — in `_api-index.mjs` |
 *
 * Split out under the 500-line cap. The seam is the one the caller already
 * uses: `api-report.mjs` hands each of these the list of sections and compares
 * the STRING that comes back against the committed file. Nothing here writes,
 * which is what keeps the write/`--check` split in one place — a generator that
 * wrote its own output could pass `--check` against a file it had just
 * refreshed.
 */

import { readFileSync } from "node:fs";
import { relative } from "node:path";
import { reportSource, stripPackageDocumentationMarker } from "./_api-surface.mjs";
import { repoRoot } from "./_fs.mjs";

/** The combined file: every entry point's report, in reading order. */
export const COMBINED_FILE = "API.md";

/** The export-name lists: what each entry point exposes, without signatures. */
export const EXPORTS_FILE = "API-EXPORTS.json";

/** Resolved here rather than passed in — every caller would pass the same one. */
const ROOT = repoRoot(import.meta.url).replace(/\/$/, "");

/**
 * The `.d.ts` rollup out of one report, without the per-file markdown wrapper.
 *
 * A report is a two-line preamble and then everything of substance inside a
 * single ```ts fence. Repeating that preamble twenty times in the combined file
 * would cost a reader twenty "Do not edit this file" lines and tell them
 * nothing; the heading this script writes instead says which entry point they
 * are looking at, which the preamble does not.
 *
 * A missing fence THROWS rather than yielding an empty section, because the
 * combined file's whole failure mode is being silently thin: `--check` compares
 * it against a freshly built copy, so twenty empty sections would agree with
 * twenty empty sections and the gate would pass.
 */
export function rollupBody(reportPath) {
  const label = relative(ROOT, reportPath);
  const body = stripPackageDocumentationMarker(
    reportSource(readFileSync(reportPath, "utf8"), label),
  );
  if (body === "") throw new Error(`api-report: ${label} rolled up to nothing.`);
  return body;
}

/**
 * `API-EXPORTS.json`: every entry point's export NAMES, sorted.
 *
 * A second artifact over the same reports, and the split between them is the
 * point. A report answers "what is the shape of this API" and churns whenever a
 * parameter is widened, a doc comment moves, or an overload is added — which is
 * what a reviewer wants, and which also means a name quietly appearing or
 * disappearing is one line inside a hundred-line diff. This file answers only
 * "what is IN the surface", so adding an export is a one-line addition and
 * removing one is a one-line deletion, in both cases against a stable file.
 *
 * `sdk/exports.test.ts` pins some of the same names, and stays: a test fails at
 * the moment the surface moves and names the symbol, which is a different job
 * from being a reviewable fact in the diff. This covers every entry point,
 * where that test covers the ones somebody remembered to add.
 *
 * Forgotten exports are deliberately absent — `collectExportedNames` reads the
 * `export` modifier, so a type that appears in the report only because a public
 * signature mentions it is in the REPORT (where a change to it is reviewable)
 * and not in this list (which is about what a consumer can import by name).
 */
export function exportsFile(sections) {
  const surface = {};
  for (const section of sections) surface[section.specifier] = section.names;
  return `${JSON.stringify(surface, null, 2)}\n`;
}

/** The specifier a consumer actually writes: `@alexkroman1/aai/stt`, not `./stt`. */
export const importSpecifier = (packageName, subpath) =>
  subpath === "." ? packageName : `${packageName}/${subpath.replace(/^\.\//, "")}`;

/** Assemble `API.md` from the reports listed in `sections`. */
export function combinedFile(sections) {
  const out = [
    "<!-- Generated by `pnpm api-report`. Do not edit — edit the source, then regenerate. -->",
    "",
    "# Public API surface",
    "",
    "Every published entry point of every publishable package, in one file, so the",
    "whole surface can be read in a single pass — which is what a coding agent",
    "needs and what the per-entry-point reports under `packages/*/etc/` are the",
    "wrong shape for. Those reports are still the artifact a REVIEWER reads: a",
    "signature change lands in the one that owns it, and `pnpm check:api-report`",
    "gates both.",
    "",
    "Sections are the reports verbatim, so anything true of them is true here —",
    "these are the rolled-up public `.d.ts` of each entry point, not prose, and a",
    "symbol exported from two subpaths appears under both.",
    "",
    "## Contents",
    "",
  ];
  for (const section of sections) {
    out.push(`- \`${section.specifier}\` — \`${section.reportPath}\``);
  }
  for (const section of sections) {
    out.push("", `## \`${section.specifier}\``, "", "```ts", section.body, "```");
  }
  return `${out.join("\n")}\n`;
}
