// Copyright 2026 the AAI authors. MIT license.
/**
 * The three files DERIVED from the per-entry-point API reports.
 *
 * `api-report.mjs` runs API Extractor over every published entry point and
 * writes one `etc/<slug>.api.md` each — that is one job. Turning those reports
 * into the three artifacts a reader uses is another, and it shares nothing with
 * the first but the list of reports:
 *
 * | File | Answers |
 * | --- | --- |
 * | `API.md` | what is the whole surface, in one pass |
 * | `API-EXPORTS.json` | what names are IN each subpath |
 * | `API-INDEX.md` | which subpath publishes a given name |
 *
 * Split out under the 500-line cap. The seam is the one the caller already
 * uses: `api-report.mjs` hands each of these the list of sections and compares
 * the STRING that comes back against the committed file. Nothing here writes,
 * which is what keeps the write/`--check` split in one place — a generator that
 * wrote its own output could pass `--check` against a file it had just
 * refreshed.
 */

import { readFileSync } from "node:fs";
import { relative } from "node:path";
import { reportSource, stripPackageDocumentationMarker } from "./_api-surface.mjs";
import { repoRoot } from "./_fs.mjs";

/** The combined file: every entry point's report, in reading order. */
export const COMBINED_FILE = "API.md";

/** The export-name lists: what each entry point exposes, without signatures. */
export const EXPORTS_FILE = "API-EXPORTS.json";

/** The reverse index: every name, against the subpath that publishes it. */
export const INDEX_FILE = "API-INDEX.md";

/** Resolved here rather than passed in — every caller would pass the same one. */
const ROOT = repoRoot(import.meta.url).replace(/\/$/, "");

/**
 * The `.d.ts` rollup out of one report, without the per-file markdown wrapper.
 *
 * A report is a two-line preamble and then everything of substance inside a
 * single ```ts fence. Repeating that preamble twenty times in the combined file
 * would cost a reader twenty "Do not edit this file" lines and tell them
 * nothing; the heading this script writes instead says which entry point they
 * are looking at, which the preamble does not.
 *
 * A missing fence THROWS rather than yielding an empty section, because the
 * combined file's whole failure mode is being silently thin: `--check` compares
 * it against a freshly built copy, so twenty empty sections would agree with
 * twenty empty sections and the gate would pass.
 */
export function rollupBody(reportPath) {
  const label = relative(ROOT, reportPath);
  const body = stripPackageDocumentationMarker(
    reportSource(readFileSync(reportPath, "utf8"), label),
  );
  if (body === "") throw new Error(`api-report: ${label} rolled up to nothing.`);
  return body;
}

/**
 * `API-EXPORTS.json`: every entry point's export NAMES, sorted.
 *
 * A second artifact over the same reports, and the split between them is the
 * point. A report answers "what is the shape of this API" and churns whenever a
 * parameter is widened, a doc comment moves, or an overload is added — which is
 * what a reviewer wants, and which also means a name quietly appearing or
 * disappearing is one line inside a hundred-line diff. This file answers only
 * "what is IN the surface", so adding an export is a one-line addition and
 * removing one is a one-line deletion, in both cases against a stable file.
 *
 * `sdk/exports.test.ts` pins some of the same names, and stays: a test fails at
 * the moment the surface moves and names the symbol, which is a different job
 * from being a reviewable fact in the diff. This covers every entry point,
 * where that test covers the ones somebody remembered to add.
 *
 * Forgotten exports are deliberately absent — `collectExportedNames` reads the
 * `export` modifier, so a type that appears in the report only because a public
 * signature mentions it is in the REPORT (where a change to it is reviewable)
 * and not in this list (which is about what a consumer can import by name).
 */
export function exportsFile(sections) {
  const surface = {};
  for (const section of sections) surface[section.specifier] = section.names;
  return `${JSON.stringify(surface, null, 2)}\n`;
}

/**
 * Code-unit order, never `localeCompare`.
 *
 * Same rule the export lists sort under and for the same reason: with no
 * explicit locale `localeCompare` answers to the runtime's ICU default, so the
 * same tree would produce a different file on a different machine and the gate
 * would report a surface change that is really a locale change.
 */
function byCodeUnit(a, b) {
  if (a < b) return -1;
  return a > b ? 1 : 0;
}

/**
 * Subpaths whose reader is the FRAMEWORK, listed apart in the index below.
 *
 * A deny-list rather than an allow-list, for the reason the config schema and
 * the contract tree both use one: a new subpath defaults into the authoring
 * half and has to be argued out, where an allow-list would silently leave it
 * uncovered. Both of these say so in their own module docs — they are
 * cross-package infrastructure, not public API, and not covered by semver.
 */
const INTERNAL_SUBPATH = /\/(?:internal|host-internal)$/;

/**
 * The floor under {@link indexFile}'s authoring half, set from the measured
 * actual (823 at the time of writing) with room to shrink.
 *
 * Every gate in this repo whose success output is a COUNT carries one, because
 * a scan that stopped matching prints the same checkmark as a healthy tree.
 * `--check` compares content, so a broken extraction fails there first — but it
 * fails as "out of date", which invites regenerating and committing the empty
 * file. The floor makes the writer refuse instead.
 */
const MIN_INDEXED_SYMBOLS = 600;

/**
 * `API-INDEX.md`: every published name, and the subpath(s) that publish it.
 *
 * The third derived artifact over the same reports, and the question it answers
 * is the one neither of the others can. A report says what a subpath's shape is
 * and `API-EXPORTS.json` says what is in each subpath — both indexed BY
 * subpath, which is the wrong direction for the question a reader actually
 * arrives with. Thirty-six subpaths publish 1,100-odd names, so "which import
 * gives me `WorkflowInputOf`?" was a grep across a JSON file or a guess, and a
 * guess is what the split between `@alexkroman1/aai` and
 * `@alexkroman1/aai/workflow-api` is least survivable at.
 *
 * A name published from more than one subpath lists all of them, in export
 * order, because that is the case worth seeing: fifty-one names are, some as
 * one declaration with two reference pages (the SDK and the browser client
 * naming the two ends of one wire) and some as a root convenience over a
 * narrower subpath. The index states the fact and the two pages argue it.
 *
 * The internal half is listed too rather than dropped — "where does this name
 * come from" has an answer for a framework name as well — but under its own
 * heading, so the authoring half is what a reader lands in.
 */
export function indexFile(sections) {
  const authoring = new Map();
  const internal = new Map();
  for (const section of sections) {
    const target = INTERNAL_SUBPATH.test(section.specifier) ? internal : authoring;
    for (const name of section.names) {
      if (!target.has(name)) target.set(name, []);
      target.get(name).push(section.specifier);
    }
  }
  // A name on both halves is an AUTHORING name: the internal subpath re-exports
  // a good few of them, and listing it twice would say the reader has a choice.
  for (const name of authoring.keys()) internal.delete(name);

  if (authoring.size < MIN_INDEXED_SYMBOLS) {
    throw new Error(
      `api-report: ${INDEX_FILE} indexed ${authoring.size} authoring symbol(s), ` +
        `under the floor of ${MIN_INDEXED_SYMBOLS}. Either the export scan stopped ` +
        "matching or the surface really shrank — check which before lowering it.",
    );
  }

  const rows = (entries) =>
    [...entries]
      .sort(([a], [b]) => byCodeUnit(a, b))
      .map(
        ([name, specifiers]) => `| \`${name}\` | ${specifiers.map((s) => `\`${s}\``).join(", ")} |`,
      );

  return [
    "<!-- Generated by `pnpm api-report`. Do not edit — edit the source, then regenerate. -->",
    "",
    "# Where each published name comes from",
    "",
    "Every export of every publishable package, and the subpath to import it",
    "from. `API.md` is the same surface indexed by subpath, with signatures;",
    "this is the reverse index, for when you have the name and want the import.",
    "",
    "A name listed against more than one subpath is published from each of them.",
    "That is usually one declaration with two reference pages — the SDK and the",
    "browser client naming the two ends of one wire, or a root convenience over a",
    "narrower subpath — so either import is correct and the pages say which reader",
    "each is for.",
    "",
    "## Authoring surface",
    "",
    "| Name | Import from |",
    "| --- | --- |",
    ...rows(authoring),
    "",
    "## Framework internals",
    "",
    "Not public API and not covered by semver — listed so a name found in a stack",
    "trace or a type error can be traced back to something.",
    "",
    "| Name | Import from |",
    "| --- | --- |",
    ...rows(internal),
    "",
  ].join("\n");
}

/** The specifier a consumer actually writes: `@alexkroman1/aai/stt`, not `./stt`. */
export const importSpecifier = (packageName, subpath) =>
  subpath === "." ? packageName : `${packageName}/${subpath.replace(/^\.\//, "")}`;

/** Assemble `API.md` from the reports listed in `sections`. */
export function combinedFile(sections) {
  const out = [
    "<!-- Generated by `pnpm api-report`. Do not edit — edit the source, then regenerate. -->",
    "",
    "# Public API surface",
    "",
    "Every published entry point of every publishable package, in one file, so the",
    "whole surface can be read in a single pass — which is what a coding agent",
    "needs and what the per-entry-point reports under `packages/*/etc/` are the",
    "wrong shape for. Those reports are still the artifact a REVIEWER reads: a",
    "signature change lands in the one that owns it, and `pnpm check:api-report`",
    "gates both.",
    "",
    "Sections are the reports verbatim, so anything true of them is true here —",
    "these are the rolled-up public `.d.ts` of each entry point, not prose, and a",
    "symbol exported from two subpaths appears under both.",
    "",
    "## Contents",
    "",
  ];
  for (const section of sections) {
    out.push(`- \`${section.specifier}\` — \`${section.reportPath}\``);
  }
  for (const section of sections) {
    out.push("", `## \`${section.specifier}\``, "", "```ts", section.body, "```");
  }
  return `${out.join("\n")}\n`;
}
