// Copyright 2026 the AAI authors. MIT license.
/**
 * The module's first test — it shipped with none, on the conversion every
 * provider socket, the browser client and both carriers go through.
 *
 * The oracle is `DataView.getInt16(i * 2, true)`, which is the only spelling
 * in the language that says "little-endian" out loud. `new Int16Array(buffer)`
 * — what the zero-copy paths use — reads in the HOST's order, so a test
 * written against it would assert the implementation against itself and agree
 * on every machine, including a big-endian one where both are wrong.
 */
import fc from "fast-check";
import { describe, expect, test } from "vitest";
import { bytesToPcm16, copyPcm16Le, copyPcm16LeBytes, pcm16ToBytes } from "./_pcm.ts";

/** The true little-endian reading of `bytes`, dropping a trailing odd byte. */
function leOracle(bytes: Uint8Array): number[] {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const out: number[] = [];
  for (let i = 0; i + 1 < bytes.byteLength; i += 2) out.push(view.getInt16(i, true));
  return out;
}

/**
 * A `Uint8Array` view at a generated byte offset inside a larger buffer, which
 * is what these functions actually receive: a base64 decode, a socket frame
 * and a `subarray` all hand over a window rather than a whole buffer, and the
 * offset is what decides which of the two branches runs.
 */
const byteViews = fc
  .record({
    prefix: fc.nat({ max: 5 }),
    body: fc.array(fc.integer({ min: 0, max: 255 }), { maxLength: 40 }),
    suffix: fc.nat({ max: 5 }),
  })
  .map(({ prefix, body, suffix }) => {
    const buffer = new ArrayBuffer(prefix + body.length + suffix);
    const whole = new Uint8Array(buffer);
    whole.set(body, prefix);
    return new Uint8Array(buffer, prefix, body.length);
  });

const samples = fc
  .array(fc.integer({ min: -32_768, max: 32_767 }), { maxLength: 40 })
  .map((values) => Int16Array.from(values));

describe("bytesToPcm16", () => {
  test("reads little-endian, whichever branch it takes", () => {
    fc.assert(
      fc.property(byteViews, (bytes) => {
        expect([...bytesToPcm16(bytes)]).toEqual(leOracle(bytes));
      }),
    );
  });

  test("little-endian is an actual choice — the other reading differs", () => {
    // Without this the property above could pass against a module that had
    // made no choice at all, which is what it did: `0x0102` is 513 read one
    // way and 258 the other, so the two readings are distinguishable and the
    // oracle is discriminating rather than decorative.
    const bytes = Uint8Array.of(0x01, 0x02, 0xff, 0x7f);
    expect([...bytesToPcm16(bytes)]).toEqual([513, 32_767]);
    const view = new DataView(bytes.buffer);
    expect([view.getInt16(0, false), view.getInt16(2, false)]).toEqual([258, -129]);
  });

  test("an aligned view is a VIEW — the module's whole reason to exist", () => {
    // Nothing asserted this. It is the reason the function is not simply a
    // copy: the pipeline hands every inbound audio frame through it, so an
    // extra allocation per frame is the cost being avoided, and a caller
    // mutating the bytes afterwards would see the samples change.
    const buffer = new ArrayBuffer(8);
    const bytes = new Uint8Array(buffer, 2, 4);
    bytes.set([1, 2, 3, 4]);
    const pcm = bytesToPcm16(bytes);
    expect(pcm.buffer).toBe(buffer);
    expect(pcm.byteOffset).toBe(2);
    bytes[0] = 0xff;
    expect(pcm[0]).toBe(leOracle(bytes)[0]);
  });

  test("an odd byte offset is a COPY, isolated from the source", () => {
    const buffer = new ArrayBuffer(8);
    const bytes = new Uint8Array(buffer, 1, 4);
    bytes.set([1, 2, 3, 4]);
    const pcm = bytesToPcm16(bytes);
    expect(pcm.buffer).not.toBe(buffer);
    expect([...pcm]).toEqual([513, 1027]);
    bytes[0] = 0xff;
    expect(pcm[0]).toBe(513);
  });

  test("an odd byte LENGTH copies too, dropping the trailing byte", () => {
    const buffer = new ArrayBuffer(8);
    const bytes = new Uint8Array(buffer, 2, 5);
    bytes.set([1, 2, 3, 4, 5]);
    const pcm = bytesToPcm16(bytes);
    expect(pcm.buffer).not.toBe(buffer);
    expect([...pcm]).toEqual([513, 1027]);
  });

  test("handles an empty view", () => {
    expect([...bytesToPcm16(new Uint8Array(0))]).toEqual([]);
  });
});

describe("pcm16ToBytes", () => {
  test("writes little-endian", () => {
    fc.assert(
      fc.property(samples, (pcm) => {
        expect([...bytesToPcm16(pcm16ToBytes(pcm))]).toEqual([...pcm]);
        expect([...pcm16ToBytes(pcm)]).toEqual([...copyPcm16LeBytes(pcm)]);
      }),
    );
  });

  test("aliases the samples' buffer, offset included", () => {
    // The documented hazard ("callers must not retain it past the point where
    // the samples may be reused") is only real because this aliases, and the
    // offset half is what a `subarray` exercises.
    const pcm = Int16Array.of(-1, 258, 3);
    const bytes = pcm16ToBytes(pcm);
    expect(bytes.buffer).toBe(pcm.buffer);
    expect([...bytes]).toEqual([255, 255, 2, 1, 3, 0]);
    pcm[0] = 0;
    expect([...bytes]).toEqual([0, 0, 2, 1, 3, 0]);
    expect(pcm16ToBytes(pcm.subarray(1)).byteOffset).toBe(2);
  });

  test("handles empty samples", () => {
    expect([...pcm16ToBytes(new Int16Array(0))]).toEqual([]);
  });
});

describe("the explicit little-endian paths", () => {
  test("copyPcm16Le matches the oracle and never aliases", () => {
    fc.assert(
      fc.property(byteViews, (bytes) => {
        const pcm = copyPcm16Le(bytes);
        expect([...pcm]).toEqual(leOracle(bytes));
        expect(pcm.buffer).not.toBe(bytes.buffer);
      }),
    );
  });

  test("copyPcm16LeBytes inverts copyPcm16Le", () => {
    // Totality in both directions: these two are what a big-endian host runs
    // for EVERY frame, so they are the pair that cannot be checked by any
    // machine in CI and therefore have to be checked directly rather than
    // through the functions that select them.
    fc.assert(
      fc.property(samples, (pcm) => {
        expect([...copyPcm16Le(copyPcm16LeBytes(pcm))]).toEqual([...pcm]);
      }),
    );
  });

  test("copyPcm16LeBytes writes the low byte first", () => {
    expect([...copyPcm16LeBytes(Int16Array.of(513, -129))]).toEqual([1, 2, 127, 255]);
  });
});
