import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/client-dir.ts",
    "src/internal.ts",
    "src/session-core.ts",
    "src/types.ts",
    "src/audio.ts",
    "src/define-client.tsx",
    "src/context.ts",
    "src/hooks.ts",
    "src/components/button.tsx",
    "src/components/chat-view.tsx",
    "src/components/controls.tsx",
    "src/components/message-list.tsx",
    "src/components/sidebar-layout.tsx",
    "src/components/start-screen.tsx",
    "src/components/tool-call-block.tsx",
    "src/worklets/capture-processor.ts",
    "src/worklets/playback-processor.ts",
  ],
  format: "esm",
  target: "es2022",
  outDir: "dist",
  dts: false,
  outExtensions: () => ({ js: ".js" }),
  deps: { neverBundle: [/^[^./]/] },
});
