import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/session.ts",
    "src/types.ts",
    "src/audio.ts",
    "src/define-client.tsx",
    "src/client-context.ts",
    "src/signals.ts",
    "src/components/app.tsx",
    "src/components/button.tsx",
    "src/components/chat-view.tsx",
    "src/components/controls.tsx",
    "src/components/error-banner.tsx",
    "src/components/message-bubble.tsx",
    "src/components/message-list.tsx",
    "src/components/sidebar-layout.tsx",
    "src/components/start-screen.tsx",
    "src/components/state-indicator.tsx",
    "src/components/thinking-indicator.tsx",
    "src/components/tool-call-block.tsx",
    "src/components/tool-icons.tsx",
    "src/components/transcript.tsx",
    "src/worklets/capture-processor.ts",
    "src/worklets/playback-processor.ts",
  ],
  format: "esm",
  target: "es2022",
  outDir: "dist",
  dts: false,
  outExtensions: () => ({ js: ".js" }),
  deps: { neverBundle: [/^[^./]/] },
});
