import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "index.ts",
    "session.ts",
    "types.ts",
    "audio.ts",
    "define-client.tsx",
    "context.ts",
    "hooks.ts",
    "components/app.tsx",
    "components/button.tsx",
    "components/chat-view.tsx",
    "components/controls.tsx",
    "components/error-banner.tsx",
    "components/message-bubble.tsx",
    "components/message-list.tsx",
    "components/sidebar-layout.tsx",
    "components/start-screen.tsx",
    "components/state-indicator.tsx",
    "components/thinking-indicator.tsx",
    "components/tool-call-block.tsx",
    "components/tool-icons.tsx",
    "components/transcript.tsx",
    "worklets/capture-processor.ts",
    "worklets/playback-processor.ts",
  ],
  format: "esm",
  target: "es2022",
  outDir: "dist",
  dts: false,
  outExtensions: () => ({ js: ".js" }),
  deps: { neverBundle: [/^[^./]/] },
});
