-- Deny-all row-level security on the platform schema.
--
-- This is DEFENSE IN DEPTH, not access control, and the distinction decides
-- everything about how it is written.
--
-- Nothing the platform does goes through RLS. It connects as the table OWNER
-- (`postgres`, over SUPABASE_DB_URL) and owners bypass policies; Realtime
-- subscribes as `service_role`, which holds BYPASSRLS — which is exactly why
-- Supabase's own docs say never to hand that key to a client. So every
-- statement below is inert for every path in use today.
--
-- What they change is the FAILURE MODE of a mistake nobody would catch.
-- Until now, the only thing between a browser and every tenant's workspace
-- was the ABSENCE of a grant (see the grant block in the platform-schema
-- migration). Add `grant select … to authenticated`, or add `aai_platform` to
-- the project's exposed-schema list, and every row becomes readable — with
-- nothing anywhere reporting it, because Supabase's linter (splinter rule
-- 0013, `rls_disabled_in_public`) and the RLS-disabled email alerts both key
-- on the `public` schema, which this is not. With RLS enabled and no policies,
-- that same mistake returns zero rows.
--
-- ENABLE, never FORCE. `force row level security` applies policies to the
-- table owner as well — and the owner is every query the platform makes, so
-- forcing it would lock the service out of its own control plane. There is a
-- test asserting the word never appears here.
--
-- NO POLICIES, on purpose. A policy would be a claim that some non-owner role
-- ought to read these tables. None should: every legitimate reader is the
-- platform itself, holding the owner or service-role connection. If a browser
-- ever reads `aai_platform` directly, that is a design change (see
-- `packages/aai-server/CLAUDE.md`, "Where we differ from Supabase's own
-- recommendations") and it arrives with its own policies.
--
-- ── THE WALRUS CLAIM — NOW COVERED BY A TEST ────────────────────────────────
--
-- These statements rest on one claim: that walrus — Realtime's per-subscriber
-- row-visibility filter — still sees rows for a BYPASSRLS subscriber once RLS
-- is enabled on the table. The failure if it does not is the SILENT one this
-- platform has already been bitten by: filtered subscribes stop, the service
-- boots healthy, and it merely stops invalidating resident sandboxes and
-- pushing studio SSE.
--
-- This block used to say the claim "cannot be checked from a test suite" and
-- asked for a staging project. That was true only for as long as no test
-- environment had a Realtime in it. A local `supabase start` stack does, so
-- `packages/aai-server/realtime-rls.integration.test.ts` now drives the real
-- `createRealtimePlatformEvents` against these very statements and asserts:
-- service_role still receives changes on both an unfiltered and a FILTERED
-- channel, and an anon subscriber receives nothing. It was mutation-tested
-- against a deliberately mis-granted schema, where it observed the leak, so a
-- green run is worth something.
--
-- Two app-level checks are still worth doing by hand against a real project,
-- because they exercise the same subscription one layer up — through the SSE
-- routes and the sandbox-invalidation path, neither of which the test boots:
--   1. Editing a studio workspace still pushes a `project` frame on
--      `GET /studio/projects/:project/events`.
--   2. Redeploying an agent still retires the resident sandbox for its slug
--      (a `Sandbox retired` / handover log line, not a silent no-op).
-- If either is dead, the cause is this migration and not the network.

alter table aai_platform.agents enable row level security;
alter table aai_platform.studio_workspaces enable row level security;
alter table aai_platform.studio_chats enable row level security;

-- Not in the publication, and covered for the same reason: they hold the same
-- tenant-identifying data (a scope hash, a project name, live sandbox tokens)
-- and carry the same accidental-grant risk. `studio_sessions` is the sharper
-- of the two — its rows contain a guest's `chat_token` and `sandbox_token`.
alter table aai_platform.studio_rate_limits enable row level security;
alter table aai_platform.studio_sessions enable row level security;
