-- The DevKit's own `workflow` schema, vendored from @workflow/world-postgres.
--
-- GENERATED by scripts/sync-workflow-schema.mjs — do not edit by hand. That
-- script's module doc carries the argument: why the platform's journal needs a
-- creator at all, why it is a migration rather than boot-time DDL, and why the
-- copy is gated (`pnpm check:workflow-schema`) rather than trusted.
--
-- This is drizzle's own migrate algorithm (`pg-core/dialect.cjs`): compare each
-- journal entry's `when` against the greatest `created_at` in their bookkeeping
-- table, apply and record what is newer. So it is idempotent, and it is a no-op
-- in both directions against `@workflow/world-postgres`'s own `bootstrap` —
-- whichever runs second finds nothing to do.
--
-- The `-- devkit-entry:` lines below are how the gate knows what is covered;
-- they are read back out of every committed migration, so there is no second
-- manifest to go stale. New entries in a later package version become a NEW
-- migration, never an edit to this one.

-- devkit-entry: 0000_cultured_the_anarchist 1762873019948 e92421745b2346049a277afbce781da3f260e68067eb1bdbd7d10bbf2ad2e743
-- devkit-entry: 0001_tricky_sersi 1763903867386 5bb606a2a55a2095101907d62d28917091316d9cddcdff5e8fc9a43e2e6f7a30
-- devkit-entry: 0002_add_expired_at 1764815363008 ac88e448e940f38bf18f076dde2abe63b53659a4c9936325e4e44cf95434e311
-- devkit-entry: 0003_add_stream_run_id 1765900000000 ad911e947a121b1def77b7ad37bd95ae7de2b453a05645e9b40f979a166e79b9
-- devkit-entry: 0004_remove_run_pause_status 1765900000001 673b7222d0df6c2fd2d335072a9d85b695b5dae4a2c52b287d2aaa5d31d462f9
-- devkit-entry: 0005_add_spec_version 1767723210726 7c3f3b73a707af2386f5c20b953e4c54631be616bf0b9bfa8ced1b97018ad384
-- devkit-entry: 0006_add_error_cbor 1768500000000 928760bfbdd23576f119f3f14c3e6db78fb765cfd24f8595c70536cb975c7178
-- devkit-entry: 0007_add_waits_table 1769500000000 f904ecb9232a269f599b393fa4ce5e3762a8267d111ad103d56fdcd11837fdcd
-- devkit-entry: 0008_migrate_pgboss_to_graphile 1770000000000 e424a48df5a1ddd752e4d09f05696e76da94e366b3d617ca10c3d3fbcdb74c77
-- devkit-entry: 0009_add_is_webhook 1770500000000 eafc36b3c9b1aaff44cd33cff9126bd7fdd796d2672b104125c32d91e0ce5597
-- devkit-entry: 0010_add_events_entity_creation_unique_index 1771000000000 5584c9be57e2c0d82fa1e972d5ee5da711b31368fbf8efee16cd2857e071af41
-- devkit-entry: 0015_move_enums_to_workflow_schema 1782691200000 adc88e08a9a0bba0bd13962db0c317b4e4aab4c6ae6ec281f2453dee9e4199c7

do $aai_devkit$
declare
  last_applied bigint;
begin
  create schema if not exists workflow_drizzle;
  create table if not exists workflow_drizzle.workflow_migrations (
    id serial primary key,
    hash text not null,
    created_at bigint
  );
  select max(created_at) into last_applied
    from workflow_drizzle.workflow_migrations;
  if last_applied is null or last_applied < 1762873019948 then
    raise notice 'applying @workflow/world-postgres 0000_cultured_the_anarchist';
    execute $aai_devkit_ddl$
CREATE SCHEMA "workflow";
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."step_status" AS ENUM('pending', 'running', 'completed', 'failed', 'cancelled');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."status" AS ENUM('pending', 'running', 'completed', 'failed', 'paused', 'cancelled');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_events" (
	"id" varchar PRIMARY KEY NOT NULL,
	"type" varchar NOT NULL,
	"correlation_id" varchar,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"run_id" varchar NOT NULL,
	"payload" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_hooks" (
	"run_id" varchar NOT NULL,
	"hook_id" varchar PRIMARY KEY NOT NULL,
	"token" varchar NOT NULL,
	"owner_id" varchar NOT NULL,
	"project_id" varchar NOT NULL,
	"environment" varchar NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_runs" (
	"id" varchar PRIMARY KEY NOT NULL,
	"output" jsonb,
	"deployment_id" varchar NOT NULL,
	"status" "status" NOT NULL,
	"name" varchar NOT NULL,
	"execution_context" jsonb,
	"input" jsonb NOT NULL,
	"error" text,
	"error_code" varchar,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"started_at" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_steps" (
	"run_id" varchar NOT NULL,
	"step_id" varchar PRIMARY KEY NOT NULL,
	"step_name" varchar NOT NULL,
	"status" "step_status" NOT NULL,
	"input" jsonb NOT NULL,
	"output" jsonb,
	"error" text,
	"error_code" varchar,
	"attempt" integer NOT NULL,
	"started_at" timestamp,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"retry_after" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_stream_chunks" (
	"id" varchar NOT NULL,
	"stream_id" varchar NOT NULL,
	"data" "bytea" NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"eof" boolean NOT NULL,
	CONSTRAINT "workflow_stream_chunks_stream_id_id_pk" PRIMARY KEY("stream_id","id")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_events_run_id_index" ON "workflow"."workflow_events" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_events_correlation_id_index" ON "workflow"."workflow_events" USING btree ("correlation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_hooks_run_id_index" ON "workflow"."workflow_hooks" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_hooks_token_index" ON "workflow"."workflow_hooks" USING btree ("token");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_runs_name_index" ON "workflow"."workflow_runs" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_runs_status_index" ON "workflow"."workflow_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_steps_run_id_index" ON "workflow"."workflow_steps" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_steps_status_index" ON "workflow"."workflow_steps" USING btree ("status");
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('e92421745b2346049a277afbce781da3f260e68067eb1bdbd7d10bbf2ad2e743', 1762873019948);
    last_applied := 1762873019948;
  end if;

  if last_applied is null or last_applied < 1763903867386 then
    raise notice 'applying @workflow/world-postgres 0001_tricky_sersi';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_runs" ALTER COLUMN "input" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" ALTER COLUMN "input" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_events" ADD COLUMN "payload_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_hooks" ADD COLUMN "metadata_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "output_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "execution_context_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "input_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" ADD COLUMN "input_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" ADD COLUMN "output_cbor" "bytea";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" DROP COLUMN "error_code";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" DROP COLUMN "error_code";
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('5bb606a2a55a2095101907d62d28917091316d9cddcdff5e8fc9a43e2e6f7a30', 1763903867386);
    last_applied := 1763903867386;
  end if;

  if last_applied is null or last_applied < 1764815363008 then
    raise notice 'applying @workflow/world-postgres 0002_add_expired_at';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "expired_at" timestamp;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('ac88e448e940f38bf18f076dde2abe63b53659a4c9936325e4e44cf95434e311', 1764815363008);
    last_applied := 1764815363008;
  end if;

  if last_applied is null or last_applied < 1765900000000 then
    raise notice 'applying @workflow/world-postgres 0003_add_stream_run_id';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_stream_chunks" ADD COLUMN "run_id" varchar;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_stream_chunks_run_id_index" ON "workflow"."workflow_stream_chunks" USING btree ("run_id");
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('ad911e947a121b1def77b7ad37bd95ae7de2b453a05645e9b40f979a166e79b9', 1765900000000);
    last_applied := 1765900000000;
  end if;

  if last_applied is null or last_applied < 1765900000001 then
    raise notice 'applying @workflow/world-postgres 0004_remove_run_pause_status';
    execute $aai_devkit_ddl$
-- Update any paused runs to cancelled
UPDATE "workflow"."workflow_runs" SET "status" = 'cancelled' WHERE "status" = 'paused';
--> statement-breakpoint
-- Create new enum type without 'paused'
CREATE TYPE "public"."status_new" AS ENUM('pending', 'running', 'completed', 'failed', 'cancelled');
--> statement-breakpoint
-- Alter column to use new type
ALTER TABLE "workflow"."workflow_runs" ALTER COLUMN "status" TYPE "public"."status_new" USING "status"::text::"public"."status_new";
--> statement-breakpoint
-- Drop old enum type
DROP TYPE "public"."status";
--> statement-breakpoint
-- Rename new enum type to original name
ALTER TYPE "public"."status_new" RENAME TO "status";
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('673b7222d0df6c2fd2d335072a9d85b695b5dae4a2c52b287d2aaa5d31d462f9', 1765900000001);
    last_applied := 1765900000001;
  end if;

  if last_applied is null or last_applied < 1767723210726 then
    raise notice 'applying @workflow/world-postgres 0005_add_spec_version';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_runs" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."status";--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('pending', 'running', 'completed', 'failed', 'cancelled');--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" ALTER COLUMN "status" SET DATA TYPE "public"."status" USING "status"::"public"."status";--> statement-breakpoint
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "spec_version" varchar;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('7c3f3b73a707af2386f5c20b953e4c54631be616bf0b9bfa8ced1b97018ad384', 1767723210726);
    last_applied := 1767723210726;
  end if;

  if last_applied is null or last_applied < 1768500000000 then
    raise notice 'applying @workflow/world-postgres 0006_add_error_cbor';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_runs" ADD COLUMN "error_cbor" bytea;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" ADD COLUMN "error_cbor" bytea;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_steps" ADD COLUMN "spec_version" integer;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_hooks" ADD COLUMN "spec_version" integer;--> statement-breakpoint
ALTER TABLE "workflow"."workflow_events" ADD COLUMN "spec_version" integer;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('928760bfbdd23576f119f3f14c3e6db78fb765cfd24f8595c70536cb975c7178', 1768500000000);
    last_applied := 1768500000000;
  end if;

  if last_applied is null or last_applied < 1769500000000 then
    raise notice 'applying @workflow/world-postgres 0007_add_waits_table';
    execute $aai_devkit_ddl$
CREATE TYPE "public"."wait_status" AS ENUM('waiting', 'completed');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow"."workflow_waits" (
	"wait_id" varchar PRIMARY KEY NOT NULL,
	"run_id" varchar NOT NULL,
	"status" "wait_status" NOT NULL,
	"resume_at" timestamp,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"spec_version" integer
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_waits_run_id_index" ON "workflow"."workflow_waits" USING btree ("run_id");
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('f904ecb9232a269f599b393fa4ce5e3762a8267d111ad103d56fdcd11837fdcd', 1769500000000);
    last_applied := 1769500000000;
  end if;

  if last_applied is null or last_applied < 1770000000000 then
    raise notice 'applying @workflow/world-postgres 0008_migrate_pgboss_to_graphile';
    execute $aai_devkit_ddl$
-- Migrate pending pg-boss jobs to a staging table before dropping the pgboss schema.
-- The application code will re-enqueue these jobs into graphile-worker on first start.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'pgboss') THEN
    CREATE TABLE IF NOT EXISTS "workflow"."_pgboss_pending_jobs" (
      name text NOT NULL,
      data jsonb,
      singleton_key text,
      retry_limit integer
    );

    INSERT INTO "workflow"."_pgboss_pending_jobs" (name, data, singleton_key, retry_limit)
    SELECT name, data, singleton_key, retry_limit
    FROM pgboss.job
    WHERE state IN ('created', 'retry');

    DROP SCHEMA pgboss CASCADE;
  END IF;
END $$;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('e424a48df5a1ddd752e4d09f05696e76da94e366b3d617ca10c3d3fbcdb74c77', 1770000000000);
    last_applied := 1770000000000;
  end if;

  if last_applied is null or last_applied < 1770500000000 then
    raise notice 'applying @workflow/world-postgres 0009_add_is_webhook';
    execute $aai_devkit_ddl$
ALTER TABLE "workflow"."workflow_hooks" ADD COLUMN "is_webhook" boolean DEFAULT true;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('eafc36b3c9b1aaff44cd33cff9126bd7fdd796d2672b104125c32d91e0ce5597', 1770500000000);
    last_applied := 1770500000000;
  end if;

  if last_applied is null or last_applied < 1771000000000 then
    raise notice 'applying @workflow/world-postgres 0010_add_events_entity_creation_unique_index';
    execute $aai_devkit_ddl$
-- Enforce uniqueness of (run_id, correlation_id, event_type) for the
-- entity-creating events (step_created, hook_created, wait_created).
--
-- Without this constraint, two concurrent runtime invocations producing
-- identical correlationIds (e.g. the snapshot runtime's deterministic
-- ULIDs across replays of the same resumption) can both insert events,
-- causing duplicate step/hook/wait events in the log. The unique
-- violation is caught in events.create and surfaced as
-- EntityConflictError, which the runtime already handles as a dedup
-- signal.
--
-- Existing installations may already contain duplicate
-- (run_id, correlation_id, type) rows for these event types — the
-- previous storage behavior allowed them through. Deduplicate before
-- creating the unique partial index, otherwise the CREATE UNIQUE INDEX
-- statement would fail at migration time. We keep the earliest-inserted
-- row for each (run_id, correlation_id, type) tuple (lowest ctid) and
-- drop the rest. The duplicates that this removes are exactly the rows
-- that would have been rejected as `EntityConflictError` had the unique
-- index existed when they were inserted.
WITH "ranked_workflow_events" AS (
	SELECT
		ctid,
		ROW_NUMBER() OVER (
			PARTITION BY "run_id", "correlation_id", "type"
			ORDER BY ctid
		) AS "row_num"
	FROM "workflow"."workflow_events"
	WHERE "type" IN ('step_created', 'hook_created', 'wait_created')
)
DELETE FROM "workflow"."workflow_events"
WHERE ctid IN (
	SELECT ctid
	FROM "ranked_workflow_events"
	WHERE "row_num" > 1
);

CREATE UNIQUE INDEX IF NOT EXISTS "workflow_events_entity_creation_unique"
	ON "workflow"."workflow_events" ("run_id", "correlation_id", "type")
	WHERE "type" IN ('step_created', 'hook_created', 'wait_created');
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('5584c9be57e2c0d82fa1e972d5ee5da711b31368fbf8efee16cd2857e071af41', 1771000000000);
    last_applied := 1771000000000;
  end if;

  if last_applied is null or last_applied < 1782691200000 then
    raise notice 'applying @workflow/world-postgres 0015_move_enums_to_workflow_schema';
    execute $aai_devkit_ddl$
DO $$
DECLARE
  enum_name text;
  public_enum regtype;
  workflow_enum regtype;
  is_used_by_workflow_columns boolean;
  has_dependents_outside_workflow_tables boolean;
BEGIN
  FOREACH enum_name IN ARRAY ARRAY['status', 'step_status', 'wait_status'] LOOP
    public_enum := to_regtype(format('public.%I', enum_name));
    workflow_enum := to_regtype(format('workflow.%I', enum_name));

    -- Nothing to migrate when the legacy public enum does not exist, or when
    -- the enum has already been moved to the workflow schema.
    IF public_enum IS NULL OR workflow_enum IS NOT NULL THEN
      CONTINUE;
    END IF;

    -- Only move enums that are actually used by workflow table columns.
    -- pg_depend has an index on referenced objects, so this lookup is based
    -- on the enum type OID instead of scanning user data or workflow rows.
    SELECT EXISTS (
      SELECT 1
      FROM pg_depend dependency
      JOIN pg_class dependent_table
        ON dependency.classid = 'pg_class'::regclass AND dependency.objid = dependent_table.oid
      JOIN pg_namespace dependent_table_schema
        ON dependent_table_schema.oid = dependent_table.relnamespace
      WHERE dependency.refclassid = 'pg_type'::regclass
        AND dependency.refobjid = public_enum::oid
        AND dependency.objsubid > 0
        AND dependency.deptype != 'i'
        AND dependent_table_schema.nspname = 'workflow'
    ) INTO is_used_by_workflow_columns;

    IF NOT is_used_by_workflow_columns THEN
      CONTINUE;
    END IF;

    /*
      pg_depend is Postgres' dependency graph.

      We use it here as a safety check before moving the enum object itself.
      A normal workflow-owned enum has only workflow table-column dependents,
      so ALTER TYPE ... SET SCHEMA is a fast metadata change.

      If anything outside workflow tables also depends on this enum, moving it
      would silently rename that user's public enum to workflow.<enum_name>.
      In that case, leave the enum in public, warn, and continue so this cleanup
      migration does not block later migrations.
    */
    SELECT EXISTS (
      SELECT 1
      FROM pg_depend dependency
      LEFT JOIN pg_class dependent_table
        ON dependency.classid = 'pg_class'::regclass AND dependency.objid = dependent_table.oid
      LEFT JOIN pg_namespace dependent_table_schema
        ON dependent_table_schema.oid = dependent_table.relnamespace
      WHERE dependency.refclassid = 'pg_type'::regclass
        AND dependency.refobjid = public_enum::oid
        AND dependency.deptype != 'i'
        AND NOT (
          dependency.classid = 'pg_class'::regclass
          AND dependent_table_schema.nspname = 'workflow'
        )
    ) INTO has_dependents_outside_workflow_tables;

    IF has_dependents_outside_workflow_tables THEN
      RAISE WARNING 'Skipping move of public.% to workflow schema because objects outside workflow tables depend on it', enum_name;
      CONTINUE;
    END IF;

    EXECUTE format('ALTER TYPE public.%I SET SCHEMA workflow', enum_name);
  END LOOP;
END $$;
$aai_devkit_ddl$;
    insert into workflow_drizzle.workflow_migrations ("hash", "created_at")
      values ('adc88e08a9a0bba0bd13962db0c317b4e4aab4c6ae6ec281f2453dee9e4199c7', 1782691200000);
    last_applied := 1782691200000;
  end if;
end
$aai_devkit$;

do $aai_devkit_rls$
declare
  t record;
begin
  for t in select tablename from pg_tables where schemaname = 'workflow'
  loop
    execute format('alter table workflow.%I enable row level security', t.tablename);
  end loop;
  execute 'revoke all on schema workflow from public, anon, authenticated';
  execute 'revoke all on all tables in schema workflow from public, anon, authenticated';
end
$aai_devkit_rls$;
